- accel.c
- allvars.h
- domain.c
- forcetree.c
- gravpm.c
- gravshort-tree-old.c
- gravshort-tree.c
- init.c
- param.c
- petaio.c
- run.c
- runtests.c
- timestep.c
This set of cleanups:
- Fixes compile warnings
- Fixes a parsing problem I encountered with my parameter files
- Makes TypeOfTimestepCriterion an actual nullop; the parameter is declared for compatibility, but does nothing.
- Fixes an ifdef around the IonizeParams call; without this all hydro sims wil be wrong!
- Removes ADAPTIVE_GRAVSOFT_FORGAS_HSML
- Removes NoTreeType as it is non-functional. Another way to make particle neutrino sims work is pending.
- Avoids computing initial smoothing lengths for DM particles. This was mainly a problem with NoTreeType, which I later removed anyway, but is I think a generally good cleanup.
> For yufeng: another set of cleanups from me

- blackhole.c
- density.c
- endrun.c
- endrun.h
- fof.c
- gravshort-pair.c
- gravshort-tree-old.c
- gravshort-tree.c
- gravshort.h
- hydra.c
- sfr_eff.c
- treewalk.c
- treewalk.h
This PR allows minimizes the treewalk interface, allows treewalk on any active set, updates a few names in treewalk, and eliminates almost all force related module global temp-variables.
- The code did ran to z=0 without dying on my test. I I tested density hydra and fof are giving identical results, but I do not know if they are correct for BH and SFR/COOL. f your test is stronger better run it too..
- After merging I think we shall merge ActiveParticle and NumActiveParticle to a single object, `ActiveParticleSet` which is an object of `ParticleSet`.
- The previous point highlights the lack of automated test cases. I had some idea, I'll write it down here too:
- Upload a snapshot to amazon or somewhere with all particle types
- finish `runtests()` to compute each force component of all …
> Treewalk any list

- allvars.h
- domain.c
- domain.h
- examples/small/paramfile.gadget
- fof.c
- forcetree.c
- forcetree.h
- gravpm.c
- run.c
- sfr_eff.c
- treewalk.c
This PR removes the reference to a variety of 'Domain' objects in the source code. They are replaced with more precisely named variables, e.g. 
- Domain decomposition Tree:  TopLeaves, TopNodes, Tasks
- ForceTree : Nodes, TopLevelNodes 
algorithm for balancing is simplified. 
- for precise cumulation of cost they are all changed to int64. I hope we never overflow int64. (TimeBase is kind of big, but we still have about 40 bits)
- I hope the new code is more readable than the old one. It acts more like a state machine rather than recursion.
algorithm for update_hmax is clarified and simplified. 
- MPI_IN_PLACE looked nicer.
- Adding a struct for possibility of updating the moments with the same algorithm.
- extending this to any particle sets -- say if we want to recompute Hsml of the …
> Domain cleanup

- Makefile.rules
- allvars.h
- begrun.c
- blackhole.c
- cosmology.c
- cosmology.h
- density.c
- examples/lya/paramfile.gadget
- global.c
- gravshort-tree-old.c
- gravshort-tree.c
- hydra.c
- param.c
- proto.h
- run.c
- test/cosmology_test.c
- test/timefac_test.c
- timefac.c
- timestep.c
- timestep.h
- treewalk.c
This pull request adds some unit tests for the cosmology module and the timefac module. It then makes sure they pass.
This means:
- Porting the better growth function solutions from N-GenIC (only affects GenIC with radiation on)
- Slightly increasing the size of the lookup table in timefac.c
There are also some (largely unrelated) cleanups to the prediction functions, and I remove TypeOfOpeningCriterion because we never used it.
> Extratests

- allvars.h
- run.c
- timestep.c
- timestep.h
Explicitly remember the current state of short range Kick and Drift.
of particles, and the current state of long range Kick and Drift.
This makes the logic in prediction cleaner (compensating difference
between drift and kick).
Move the first half kick before find time step, because it is finishing
the previous time step. The second half kick uses the new time step.
The code compiles, but I suspect there are bugs.
> Cleaner time step bookkeeping.

- domain.c
- domain.h
- forcetree.c
- system.c
- system.h
This implements a drastically faster local refinement algorithm.
The main idea is to first build a full tree for a subsample of particles (current 1/16th). Then accurately count the cost and counts for each node in this tree quickly, and once. This accurate tree is then chopped off to produce the local refinement, such that each leave is smaller than the required granularity.
The secondary improvement is to avoid permuting the P data structure by the Key. We only need Key and Cost for each particle in most of the toptree meddling. Because the new data is much smaller, I required a global sorting with mpsort, this should improve the locality of the local trees, and improve the accuracy of the final merged tree.
The third improvement is to remove the poorly split logic between add_costs and …
> Better local refine

- density.c
- init.c
- proto.h
Replaces #98 
This one doesn't slow down at all because it doesn't introduce an additional tree walk every step.
It only helps to stablize the initialization iteration in pressure-entropy SPH. No other structural benefits from split smoothing from density. 
@sbird Does this look ok to you?
> Use two versions of density(), and density_update()

- allvars.h
- forcetree.c
- forcetree.h
- tests/test_forcetree.c
This PR avoids randomization by putting all particles in a small node to a linked list. These particles are marked as 'SufferFromCoupling' particles; such that we can potentially count them during the run.
> Forcetree with a linked list.

- proto.h
- system.c
Adding back MPI_Alltoallv_sparse function. Throttling option included with call to MPI_Alltoallv_sparse instead of MPI_Alltoallv.
> restart-fixes-alltoallv_sparse

- allvars.h
- init.c
- param.c
- run.c
- tests/test_timebinmgr.c
- timebinmgr.c
- timebinmgr.h
- timestep.c
This is the way to decouple sync and outputs. I think we can even
populate the sync points a bit more aggressively to avoid running out
of time bins.
I have yet to test this on a small run.
> WIP: arbitrary sync points.

- examples/travis/paramfile.gadget
- timebinmgr.c
This PR may fix the issue  from landerson, #114  where the code crashes outputting from high redshifts. It is because of a silly typo of memmove, mixing source and dest, and as a result some syncpoints / output times are lost!
> Wrong syncpoints

- allvars.h
- genic/power.c
- gravpm.c
- gravshort.h
- run.c
- runtests.c
- timebinmgr.c
Following a suggestion by Yu Feng, we do not actually need OldAcc in the particle data. 
I was originally going to create a temporary array, but I realised that because it is only used by one half of the force equation, we don't need it at all. 
To ensure this gives the same result as the previous solver,  we must perform the tree gravity first and the PM gravity second: otherwise the current PM step over-writes the last one.
I was then able to combine PM_Potential with Potential. 
I could have combined GravPM and GravAccel, but they are too useful for debugging.
> Remove OldAcc and PM_Potential from struct particle_data

- blackhole.c
- density.c
- domain.c
- drift.c
- exchange.c
- fof.c
- fofpetaio.c
- garbage.c
- hydra.c
- init.c
- peano.h
- run.c
- sfr_eff.c
- tests/test_forcetree.c
- timestep.c
- timestep.h
We found that TimeBinCount was not updated correctly in domain exchange: it was decremented for particles leaving, but not incremented for particles arriving. It was also not incremented correctly in sfr and black hole. Normally this did not matter, because rebuild_activelist was called after domain, but during FoF particles are exchanged (then returned) and rebuild_activelist is not called.
I considered a fix involving updating the TimeBinCount, but I found a simpler solution was just to avoid the need to keep it up to date. Now it is used only for printing counts just after domain. The smallest timebin is returned by find_timestep. This avoids a number of atomic updates in openmp code.
Also do not do domain_maintain after FoF: it always exchanged zero particles.
> Fix time bin count

- examples/travis/paramfile.genic
- genic/params.c
- genic/save.c
- param.c
- petaio.c
This removes the paramfile flag UsePeculiarVelocity. The behavior is now encoded in the IC file -- if IC file has legacy Gadget velocity, MP-Gadget will do a**2 dx / dt like BlueTides-i. If IC file has peculiar velocity, MP-Gadget will do peculiar velocity as well.
> save UsePeculiarVelocity in header files.

- cosmology.c
- cosmology.h
- genic/params.c
- param.c
Add parameters for a simple (w0, wa) dark energy parametrisation, so we can run simulations with dark energy models of the type most commonly used by cosmologists.
> Darkenergy

- Makefile.rules
- allvars.h
- begrun.c
- examples/travis/paramfile.gadget
- forcetree.c
- forcetree.h
- gravshort-pair.c
- gravshort-tree.c
- gravshort.h
- init.c
- param.c
- runtests.c
- tests/test_forcetree.c
- timestep.c
This largely removes the twisted Gadget logic in the handling of softening length by
1. decouple type from the softening, allowing a more natural flow of adaptive softening of gas
2. reparametrize the softening to use two parameters; eliminating the non-sense Phys softening limiter -- we argued using adaptive softening made more sense.
3. Use a single array for softenings, not two off only by a factor of 2.8.
Also fixed a potential divide by zero bug of potential calculation when adaptive softening is enabled.
> Soften cleanup

- allvars.h
- densitykernel.h
- examples/dm-only/paramfile.gadget
- examples/lya/paramfile.gadget
- param.c
- sfr_eff.c
Make the code accept the same parameters irrespective of the SFR and
BLACK_HOLES compile flags. If these compile flags are not enabled the
(optional) black hole and star parameters just do nothing.
Fixes: #147
> Make BLACK_HOLE parameters exist even if compile flag is off.

- param.c
This PR is related to PR #148 and issue #147 .
It hides BH options when MP-Gadget was compiled without the BH flag. 
I've tested that the code compiles both when the flag is ON and OFF.
> hide BH options when not compiled with BH flag

- petaio.c
So we don't run out of memory. This is a short-term hack. The longer term is to allocate star and BH memory with mymalloc2 and increase it dynamically.
> Allocate more memory for stars with quick lyman alpha star formation

- examples/lya/paramfile.genic
- init.c
- run.c
- timestep.c
The check that time is moving forward was prone to floating point and
other problems during simulation startup. Move this into run.c and only
use it after the first timestep completes.
Fixes #149
> Move 'time is forward' check into run.c

- fof.c
- fofpetaio.c
- genic/main.c
- openmpsort.c
- tests/test_openmpsort.c
- treewalk.c
- walltime.c
I noticed that system qsort, which for glibc is a merge sort, allocated O(n) temporary storage using malloc. This is not good for our memory fragmentation, especially as it does it under heavy thread contention. It is also unnecessary, as we already have temporary memory allocated for the parallelization, which we can re-use. 
I fixed this by copying glibc's qsort implementation of merge sort into openmpsort.c and renaming the temp variable. While I was there I also extended indirect sorting for large structures to the merge phase, which should help for the sort of struct particle_data in domain.c and reduces the maximum memory allocation. Another advantage of this is that a smart compiler with lto could possibly inline the comparison function.
We could probably make the sorting much …
> Memory sort

- Makefile.tests
- exchange.c
- tests/test_exchange.c
This adds a unit test for the exchange code. 
It fixes a bug: reallocing was broken if both Stars and BHs were there, because pointer arithmetic is not associative for different pointer types (duh).
It also fixes a minor suboptimality: garbage particles were put in the exchange buffer.
I did this on master instead of the slotmanager branch: this means a rebase is necessary but it also means that one can bisect if a commit in slotmanager breaks the test.
> Test exchange

- domain.c
- exchange.c
- forcetree.c
- init.c
- run.c
- slotsmanager.c
- slotsmanager.h
- tests/test_slotsmanager.c
- timestep.c
Continuing in our series of improving the garbage collection - this is a series with a few more tweaks. The differences are actually rather slight. The main commit is 9ba9d25, which adds a new garbage collection algorithm which is O(n) when compacting the slots, and preserves the (peano) order of the particles. This also lets the non-slot-compacting part avoid changing the slot array entirely, but because more data is moved, the base gc is slower. On my machine this works out to exactly the same time taken doing GC. The slot gc might be faster but with the default parameters it doesn't run very often. 
I also moved the peano sort into slotmanager and added a slot sort after it.
The main advantage is that treebuild is 20% faster on average, because the ordered particles make it easier for …
> A bit more garbage

- Makefile.rules
- Makefile.tests
- begrun.c
- endrun.c
- forcetree.c
- hci.c
- hci.h
- io.c
- proto.h
- run.c
- tests/test_forcetree.c
- tests/test_hci.c
- timebinmgr.c
- timestep.c
Updated timeout strategy that's likely more reliable:
1. queries occur on every PM step.
2. measure the longest time duration between two queries == longest
time spent between two PM steps.
3. If there isn't enough wallclocktime between now and the limit
to arrive to the next query, then we have a timeout.
> split ioctl stuff to HCI(human-computer-interaction).

- forcetree.c
When MyFloat is single hmax overlaps with the last element of suns.
setting hmax to zero breaks the tree termination condition, causing
force_get_next_node to loop forever.
This fixes #184
> fix 184, do not purge suns accidentally.

- Options.mk.example
- endrun.c
- endrun.h
- genic/main.c
- main.c
- tests/stub.c
When no tools exist it will fallback to glibc's backtrace.
The code is largely modelled from xorg-server's backtrace and osinit.
> add -DSTACKTRACE; print stack trace with an external tool.

- begrun.c
- blackhole.c
- density.c
- drift.c
- global.c
- hydra.c
- hydra.h
- init.c
- proto.h
- run.c
- sfr_eff.c
- slotsmanager.h
- timestep.c
- timestep.h
This pull request evolves entropy at drift time instead of kick time. It also fixes multiple bugs in DENSITY_INDEPENDENT_SPH that I found along the way. 
These should definitely go to stable.
e692317 - fixes a bug that the entropy change is limited in EntropyPred. This is silly because it also applies to backward predictions and thus limits the heating that can happen.
7fdcda0 - This moves the change in the units of DtEntropy into reduction rather than postprocessing. This is because EntropyPred = Entropy + DtEntropy * Dt is used to generate DtEntropy for neighbouring particles. If this happened after DtEntropy was reduction but before postprocessing the units of Dtentropy were different and so EntropyPred would give a wrong result. Also for stable.
3e1b223 and earlier commits change the …
> Driftentropy

- domain.c
We will try a few policies before bailing out, with increasing
computational cost and decreasing accuracy.
This PR fixes a bug where the TopTree split may underflow the 'shift' variable, which may be causing #171 .
> Introduce a Policy object for domain decomposition.

- genic/main.c
- hci.c
- tools/compare_snap.py
- tools/hmffromfof.py
- compare_snap.py checks whether a field has changed between snapshots (I use it all the time for development).
- hmffromfof uses the FOF output to generate a conventionally unitted halo mass function.
In future we could use it for an integration test that checks we have a
theoretically expected halo mass function.
> Add two useful python scripts

- .travis.yml
- forcetree.c
- forcetree.h
- genic/main.c
- genic/power.c
- genic/proto.h
- genic/save.c
- sfr_eff.c
- tests/test_forcetree.c
Thread the second phase of the tree build procedure, the moments calculation. This is done using a split/merge algorithm. It doesn't work particularly well with the treebuild test (because those are deliberately pathological setups) , but it scales roughly linearly with thread number up to at least 8 threads on a real simulation.
Testing done:
- dm-only example to z=3 with 8 threads and 4 mpis / 2 threads (on a hyperthreaded quad-core), and I checked the final output was the same for master and this branch in both cases. Note that the output did differ slightly between the 8 threads and 4 mpis/2 threads tests, which may need investigating.
With this the % time spent in tree build goes from 11% in the 8 thread example to 6%.
> Openmpmoments

- Makefile.tests
- allvars.h
- begrun.c
- genic/allvars.c
- genic/allvars.h
- genic/main.c
- genic/params.c
- genic/proto.h
- genic/thermal.c
- genic/thermal.h
- genic/zeldovich.c
- param.c
- run.c
- system.c
- system.h
- tests/test_genic-thermal.c
Once again allow adding thermal velocities corresponding to warm dark matter to the initial CDM distribution. Do not alter the power spectrum though - that is best done externally.
> Bring back WDM thermal velocities

- fof.c
- fof.h
- main.c
- run.c
Avoid allocating memory for qsort when base is still allocated.
I had a simulation recently where this was the point of peak memory usage: moving the allocation a little later helped, because there is no qsort allocation with both Base and Group allocated.
> Refactor fof slightly to reduce peak memory usage

- libgadget/gravshort-tree.c
- tools/plot-structure.py
This fixes a type definition in gravshort, which could have led the force softening to be truncated if we every used mixed softenings (but we don't).
It also removes the drift_particle from gravshort, which did nothing but was surprisingly hot in a profile.
Finally it adds a short script which uses nbodykit to plot the structure in a box. Just to have it handy.
> Small fixes and a small script

- Options.mk.example
- gadget/main.c
- libgadget/drift.c
- libgadget/forcetree.c
- libgadget/partmanager.c
- libgadget/partmanager.h
- libgadget/treewalk.c
- libgadget/utils/openmpsort.c
- libgadget/utils/system.h
- platform-options/Options.mk.BlueTides
- platform-options/Options.mk.cori
- platform-options/Options.mk.coriknl
- platform-options/Options.mk.edison
- platform-options/Options.mk.example.coma
- platform-options/Options.mk.example.icc
- platform-options/Options.mk.pfe
- platform-options/Options.mk.stampede2
- platform-options/Options.mk.travis
This commit fixes #217 and should fix compilation on mac. OPENMP_USE_SPINLOCK is replaced by NO_OPENMP_SPINLOCK, which compiles and enforces that the code runs in single-threaded mode. Most of the diff is actually cleanups.
> Spinlockfix

- libgadget/density.c
- libgadget/domain.c
- libgadget/fof.c
- libgadget/forcetree.c
- libgadget/gravshort-pair.c
- libgadget/gravshort-tree-old.c
- libgadget/gravshort-tree.c
- libgadget/gravshort.h
- libgadget/init.c
- libgadget/petaio.c
- libgadget/petapm.c
- libgadget/run.c
- libgadget/runtests.c
- libgadget/slotsmanager.c
- libgadget/timestep.c
- libgadget/timestep.h
- libgadget/treewalk.c
- libgadget/treewalk.h
- libgadget/utils/system.c
- libgadget/utils/system.h
Treewalk optimisations for high thread count, especially knights landing
I ran the code on Stampede's knight's landing nodes. Our performance kind of sucks (perhaps half of a normal intel skylake node). Part of this is because I was using a very small problem size, but part of it is that our code needs to be threaded better. I was able to get an extra 10% of the total runtime by careful massaging of the tree: in particular I made sure that the WorkSet queue preserves the order of particles in memory.
Making the ActiveParticle list was also a hot-spot at high thread count: I parallelized it and was able to skip it entirely during a PM step. Skipping it entirely during a PM step saved memory but didn't noticeably decrease CPU time, probably because a PM step is relatively rare.
Tested that …
> Treewalk opt

- libgadget/domain.c
- libgadget/exchange.c
- libgadget/exchange.h
- libgadget/fofpetaio.c
- libgadget/partmanager.h
- libgadget/tests/test_exchange.c
- libgadget/tests/test_memory.c
- libgadget/timestep.c
- libgadget/treewalk.c
- libgadget/utils/memory.c
- libgadget/utils/system.c
- libgadget/utils/system.h
A few changes to make the exchange faster and more thread friendly. After this all the expensive functions during exchange should be parallelized and, at the cost of some memory, some loops over all particles are avoided. The export flags are removed and replaced with an ExchangeList array (not too much of a memory cost because we no longer have an ActiveParticle list allocated during exchange).
On a KNL node with 16 threads per MPI this reduces the total exchange time by a factor of two and the non-garbage exchange time by a factor of three.
> Exchange thread scaling

- genic/main.c
- libgadget/forcetree.c
- libgadget/petapm.c
- libgadget/utils/memory.h
- libgadget/utils/mymalloc.c
While working on something else I noticed that we were spending a lot of time syncing at MPI_Barrier calls after message(0, ). So I removed the MPI_Barrier - I think it is mostly around so that we have well-measured timestamps in the log, but walltime_measure does that for us better. I get a speed-up of about 1.5% on a small 2 node, 48 MPI run, which is not large but not that small either for the size of the change.
I also removed some MPI_Barrier calls in debug functions, and stray calls in a couple of other places.
There is the possibility that removing what is effectively a sync after every major function will reveal some latent race conditions somewhere, and initially I thought this was happening, but it went away after a recompile (or maybe required a specific timing condition only …
> Remove Barriers

- gadget/params.c
- libgadget/allvars.h
- libgadget/gravshort-tree.c
- libgadget/run.c
This PR reintroduces a Barnes-Hut tree-opening criterion and uses it on the first timestep, which allows us to avoid an O(N^2) treewalk on restarts. This was done because restarting can get *very* slow at low redshift.
> Reintroduce Barnes-Hut criterion, use it on first timestep.

- libgadget/exchange.c
When an exchange has multipe iterations, it performs a garbage
collection in between them. This moves the particles, and so the
ExchangeList no longer points in the right place. Fix this by
recomputing ExchangeList inside the iteration loop.
> Fix multi-iteration exchanges

- benchmarks/dm-50-512/paramfile.gadget
- examples/dm-only/paramfile.gadget
- examples/fastpm-compat/paramfile.gadget
- examples/hydro/paramfile.gadget
- examples/linear_growth/paramfile.gadget
- examples/neutrinos/paramfile.gadget
- examples/small/paramfile.gadget
- gadget/params.c
- libgadget/allvars.h
- libgadget/blackhole.c
- libgadget/domain.c
- libgadget/exchange.c
- libgadget/fof.c
- libgadget/petapm.c
- libgadget/sfr_eff.c
- libgadget/slotsmanager.c
- libgadget/slotsmanager.h
- libgadget/tests/test_slotsmanager.c
- libgadget/timestep.c
- libgadget/treewalk.c
I ran some benchmarks with 48 threads. This addresses places where it did not scale as well as distributed memory, and does a few cleanups. 
- The GC was taking a lot of time. I first tried making it parallel and failed (because it is limited by memory bandwidth, the parallel version was not faster). I then changed the code to not do it on a short timestep (unless there is a big exchange). There is no perceptible performance change due to having garbage left floating around.
- I changed SFR and BH to just convert particles where possible, instead of creating garbage.
- I changed the treewalk buffer to just use available memory, like exchange does. This was motivated by threaded runs generally needing much larger buffers. BufferSize is no longer a parameter, but I added something to leave …
> Improve threading scalability

- examples/travis/check-results.py
window= keyword was deprecated and shall be replaced with resampler=
for good reasons.
> MAINT: update check-results for nbodykit 0.3.7

- gadget/params.c
- libgadget/allvars.h
- libgadget/blackhole.c
- libgadget/density.c
- libgadget/drift.c
- libgadget/fof.c
- libgadget/hydra.c
- libgadget/run.c
- libgadget/sfr_eff.c
- libgadget/slotsmanager.c
- libgadget/slotsmanager.h
- libgadget/tests/test_exchange.c
- libgadget/tests/test_slotsmanager.c
- libgadget/timestep.c
- libgadget/timestep.h
- libgadget/treewalk.c
- platform-options/Options.mk.travis
This series corrects three pessimizations I introduced earlier: 
9ac4abe removes a needless memset, which was taking a lot of time (20% of runtime!) since I made the buffer in question use all available memory.
9e5d93f avoids cooling dense particles that will become stars when using the quick lyman alpha star formation. This can be expensive since DoCooling is slow for dense particles.
1864109 replaces the function calls to sph_VelPred scattered around the hydro code with a variable in SPHP. I made it a function to save memory but it was very expensive! This saves about 20% of total runtime, and almost 50% of the SPH time!
While I was going I removed a few atomic variables, fixed a race condition that would never matter in practice and fixed a fixme by making the factor to expand slot …
> Optimizations

- gadget/main.c
- libgadget/fof.c
- libgadget/treewalk.c
This implements the double compare and swap algorithm suggested in: 
https://github.com/MP-Gadget/MP-Gadget/pull/245#discussion_r250711455
Fixes the deadlock, passes the tests!
I like this algorithm much better - I was also unsure about the corner cases in the last one. I think I found one when testing this, in fact.
One thing I am unsure about is whether we need to take the lock in update_root. I think we do not need to if the write is atomic, because the head is preserved. But then I think we might need an omp atomic write annotation.
> Fofthreadingfix2

- libgadget/domain.c
- libgadget/exchange.c
- libgadget/fof.c
- libgadget/forcetree.c
- libgadget/gravshort-tree-old.c
- libgadget/gravshort-tree.c
- libgadget/treewalk.c
- libgadget/utils/mymalloc.h
This fixes a crash when I am running with a single rank on a machine
with 16GB of memory.
> Do not use huge bunchsizes that causes overflow.

- libgadget/init.c
- libgadget/petaio.c
- libgadget/run.c
- libgadget/timestep.c
- libgadget/timestep.h
This fixes #251 by correctly initialising Entropy when restarting from a snapshot with DENSITY_INDEPENDENT_SPH off. We load it from the InternalEnergy array both with and without the compile flag to reduce regressions in future.
The SFR after a restart is still not exactly the same as not restarting (differs by about 0.1%) but it's close enough. I don't think we can get bit-exact equivalence because the act of forming stars changes the local density. Tested that it does fix #251 . This is an argument for removing the DENSITY_INDEPENDENT_SPH compile flag in the future.
Also a small refactoring of find_timestep that I did when I thought that was the problem.
> Fix Entropy reload

- libgadget/init.c
- libgadget/petaio.c
- libgadget/petaio.h
I think this was the source of my difficult with 254.
I'm OK with using InternalEnergy as the primary thermal state variable. 
But why scattering the conversion in both init.c and petaio when we can do the conversion one next to the other?
> follow up #254

- gadget/main.c
- gadget/params.c
- libgadget/Makefile
- libgadget/allvars.h
- libgadget/blackhole.c
- libgadget/cooling.c
- libgadget/cooling.h
- libgadget/cooling_rates.c
- libgadget/cooling_rates.h
- libgadget/cooling_uvfluc.c
- libgadget/petaio.c
- libgadget/run.c
- libgadget/sfr_eff.c
- libgadget/stats.c
- libgadget/tests/test_cooling.c
- libgadget/tests/test_cooling_rates.c
- libgadget/treewalk.c
- libgadget/treewalk.h
- libgadget/utils/endrun.c
- libgadget/utils/paramset.h
This branch reworks the cooling code. The main aim of this was to support the newer cooling rates and to add support for self-shielding following Rahmati 2012 (also used in Illustris, although the implementation I chose is a little different). To do this I had to understand the cooling code, and it was easier to rewrite that from scratch. To make sure I did this right, I also added a fair number of unit tests and comments. This follows heavily the python cooling code found in: https://github.com/sbird/fake_spectra/blob/master/fake_spectra/rate_network.py
The final test was to run the hydro example calling both the old cooling code and the new cooling code on each particle, to ensure they gave the same answer.
The cooling rates supported are now:
- The ones used in old Gadget (Cen 92)
- …
> New cooling code.

- gadget/main.c
- libgadget/blackhole.c
- libgadget/blackhole.h
- libgadget/checkpoint.c
- libgadget/checkpoint.h
- libgadget/density.c
- libgadget/density.h
- libgadget/domain.h
- libgadget/fof.c
- libgadget/fof.h
- libgadget/forcetree.c
- libgadget/forcetree.h
- libgadget/gravity.h
- libgadget/gravpm.c
- libgadget/gravshort-pair.c
- libgadget/gravshort-tree-old.c
- libgadget/gravshort-tree.c
- libgadget/hydra.c
- libgadget/hydra.h
- libgadget/init.c
- libgadget/run.c
- libgadget/runtests.c
- libgadget/sfr_eff.c
- libgadget/sfr_eff.h
- libgadget/tests/test_forcetree.c
- libgadget/treewalk.c
- libgadget/treewalk.h
- libgadget/winds.c
- libgadget/winds.h
This pull request is a pure cleanup. It removes all the mess of global variables in forcetree.c and replaces them with a single struct. Initially this is a global struct, but in the last commit it is passed around by all the functions using it. There are thus no longer any globals associated with the force tree.
I did this because I was trying to write tests for some of the tree walking routines (gravity and density) and the mess of globals was making it difficult. This PR also fixes runtests, which has been broken for ages because it didn't correctly initialize the tree.
For my next trick: the domain globals.
> Modular tree

- genic/main.c
- genic/params.c
- libgadget/allvars.h
- libgenic/allvars.c
- libgenic/allvars.h
- libgenic/glass.c
- libgenic/proto.h
- libgenic/save.c
- libgenic/zeldovich.c
This cleans up our glass file support - MakeGlass is replaced with two options, MakeGlassCDM and MakeGlassBar for baryon and CDM glass file support respectively. Neutrinos can't be put into a glass (it makes little sense). The GenIC global particle table variable is removed in preparation (for something I am about to try, but it is a cleanup that makes sense on its own).
> Cleanups to glass files and libGenIC globals

- libgadget/blackhole.c
- libgadget/cooling.c
- libgadget/cooling.h
- libgadget/cooling_rates.c
- libgadget/cooling_rates.h
- libgadget/petaio.c
- libgadget/tests/test_cooling_rates.c
get_neutral_fraction takes physical protons/cm^3, not internal gadget units.
Create new function that takes the internal units and use it.
> Fix the neutral fraction output

- libgadget/blackhole.c
- libgadget/petaio.c
- libgadget/sfr_eff.c
- libgadget/sfr_eff.h
This fixes a very old bug in Gadget: that the neutral fraction on the effective equation of state is reported as
GetNeutralFraction(egyeff) (which is usually << 1) when it should be GetNeutralFraction(egycold) * cold cloud fraction + GetNeutralFraction(egyhot) * (1- cold cloud fraction) (which is usually ~ 1). I fix this now because Jamie Bolton got caught by it in Illustris.
This normally only affects the NH0 saved in the snapshots for star-forming particles, and I would not even ask for a review if that were all. However, the second commit changes the BH_OPTHIN AGN feedback by reweighting the feedback energy more towards dense particles (in that method feedback is weighted by neutral fraction). Do we use that method anywhere? Does that seem plausible? It is certainly more physical, but …
> Sfrneutralfix

- gadget/params.c
The new rates are the ones used in Sherwood and recommended by Jamie Bolton. They are more accurate. Also enable the self-shielding correction by default, which has a slight effect at IGM densities.
This will change the output, albeit slightly. The mean flux changes by a few percent and the flux power by a similar amount (once rescaled to the same mean flux). The effect would be smaller if the temperature were also marginalized out.
@andreufont  @Chris-Pedersen : This is a flag day. Be warned!
> Change cooling defaults to new rates.

- gadget/params.c
- genic/params.c
- libgadget/utils/paramset.c
- libgadget/utils/paramset.h
- trace the origin of a parameter value (line number of default value)
- warn if a undefined optional is cast to a concrete value.
The third state is not yet used anywhere. A few cases I tried it only makes the situation harder to deal with.
I think we may want to get rid of most of the duplicated items in All / xxx params and ParameterSet at some point, the modules can cache the concrete values before entering expensive loops, and read from the paramset in other occasions; but that's more work than I can do this week.
> More code towards using the UNDEFINED state of optional parameters.

- Options.mk.example
- README.rst
- gadget/params.c
- libgadget/density.c
- libgadget/init.c
- libgadget/run.c
- libgadget/sfr_eff.c
- libgadget/sfr_eff.h
- libgadget/slotsmanager.c
- libgadget/slotsmanager.h
- platform-options/Options.mk.BlueTides
- platform-options/Options.mk.cori
- platform-options/Options.mk.coriknl
- platform-options/Options.mk.edison
- platform-options/Options.mk.example.coma
- platform-options/Options.mk.example.icc
- platform-options/Options.mk.macos
- platform-options/Options.mk.pfe
- platform-options/Options.mk.stampede2
- platform-options/Options.mk.travis
This removes the compile flag SPH_GRAD_RHO which is the LAST COMPILE TIME SCIENCE FLAG!! Hooray! No longer will we need to recompile MP-Gadget for different tests! Everything is runtime.
If you agree with the approach for sph_extra_data I might move some other things that are recomputed every timestep into it. eg, VelPred.
> Runtime SPH_GRAD_RHO

- libgadget/blackhole.c
- libgadget/density.c
- libgadget/fofpetaio.c
- libgadget/hydra.c
- libgadget/partmanager.h
- libgadget/slotsmanager.h
Shrink sph_particle_data and particle_data by making some array elements local to other modules. Move EntVarPred into sph_scratch_data. This provides a modest speed win (10% of hydro) because of the temporary array for Pressure, but the big point is to enable future work. I have checked that these commits make no difference to output of a hydro example run.
> Memoryopts

- genic/params.c
- libgadget/allvars.h
- libgadget/petaio.c
- libgadget/timestep.c
- tools/convert_bigfile_gadget_format3.py
This replaces https://github.com/MP-Gadget/MP-Gadget/pull/300
Makes UsePeculiarVelocities = 1 the default, fixes the format conversion script and adds some comments on the velocity format.
> Make UsePeculiarVelocities = 1 the default.

- libgadget/blackhole.c
- libgadget/init.c
- libgadget/sfr_eff.c
- libgadget/slotsmanager.c
- libgadget/slotsmanager.h
- libgadget/timestep.c
This moves the SPH_injected_bh out of sph_particle data the *other* way, by moving into scratch. The slightly odd behaviour of heated star-forming gas is thus preserved. This keeps all the behaviour of the old code intact.
> Injected bh

- libgadget/fof.c
- libgadget/fofpetaio.c
- libgadget/petaio.c
- libgadget/run.c
- libgadget/sfr_eff.c
- libgadget/sfr_eff.h
- libgadget/slotsmanager.c
- libgadget/slotsmanager.h
This PR fixes a segfault in the FOF code on particle write. The segfault was happening because the star formation rate calculation may use SPH.GradRho, and after the exchange in FOF SPH.GradRho may be on a different processor. There are two fixes needed. The first is to compute the neutral fraction without computing the star formation rate and the second is to store the star formation rate in the sph_particle_data struct again so that it goes with the FOF exchange.
Commit 1e47aad implements the first by refactoring the star formation rate code so that the effective equation of state parameters are computed in one function and the actual SFR in another. It does marginally change the output of the hydro run, slightly increasing the number of stars. Looking at sfr.txt it seems that the …
> Fixfofsegfault

- libgadget/density.c
- libgadget/density.h
- libgadget/init.c
- libgadget/petaio.c
- libgadget/run.c
This PR cleanups up the convoluted code in init, so that the initializations are now done in init.c instead of via opaque conditionals in density.c.
Apart from 3899ac2, which changes the hard-coded baryon fraction to the true one, it makes no difference to output (except that, according to a very old fixme, the black hole smoothing length is now saved). It has a very marginal positive effect on the simulation speed.
> Clean up initialisation of the densities

- gadget/params.c
- genic/params.c
- libgadget/utils/paramset.c
- libgadget/utils/paramset.h
- libgadget/utils/string.c
- libgadget/utils/string.h
Then they can be printed with endrun / message, thus not swallowed
by the super computers at crash.
> Pass some of the errors as return values.

- libgadget/Makefile
- libgadget/blackhole.c
- libgadget/drift.c
- libgadget/drift.h
- libgadget/fof.c
- libgadget/forcetree.c
- libgadget/gravshort-tree.c
- libgadget/partmanager.c
- libgadget/partmanager.h
- libgadget/utils.h
- libgadget/utils/spinlocks.c
- libgadget/utils/spinlocks.h
- libgadget/winds.c
This PR moves the spin locks out of struct particle_data and into their own little file. This has no measureable effect on performance or output, but it tidies up the pthread code and means we can use the same routines in the tree build.
> Locallocks

- libgadget/Makefile
- libgadget/density.c
- libgadget/forcetree.c
- libgadget/tests/test_density.c
- libgadget/tests/test_exchange.c
- libgadget/tests/test_forcetree.c
- libgadget/timefac.c
- libgadget/treewalk.c
- tests/stub.c
This adds a test for density and then fixes a few bugs connected with it. It warns if the difference between the upper and lower HSML bounds < 0.1 % of the lower bound, which is a catchall stopping condition for the code. It should never be hit in practice unless it is hiding another bug.
I also found a bug in the stopping condition for too small Hsml values. If an intermediate Hsml value was less than MinGasHsml the code would stop, even if the true Hsml should have been larger. Then there is a roundoff error induced by using the wrong condition to choose Right and Left which was causing wrong Hsml values in a small number of particles in the hydro run.
Finally I build the density redo queue as we go, which should help large simulations a bit (although I cannot measure any speed change).
> Add a density test and fix a bunch of density bugs

- libgadget/partmanager.h
- libgadget/treewalk.c
Remove setting Evaluated from the treewalk.
Replace it with inline touching up of the export list. As long as a full export buffer is rare, this speeds up the tree walk substantially. If a full export buffer is common it does nothing.
> Remove setting Evaluated from the treewalk

- libgadget/forcetree.c
This PR enforces that garbage particles are not added to the forcetree and adds an extra check to the tree build.
> Treegarbagefix

- libgadget/forcetree.c
- libgadget/forcetree.h
- libgadget/tests/test_forcetree.c
This modifies the tree build algorithm to both make the tree shallower and the tree build faster (prompted because the walking has gotten so much faster recently that build is noticeable again).
On a small run on my desktop this halves the treebuild time and speeds up density and hydro substantially (maybe 20-30%).
Instead of keeping adding each particle to a specific quadrant and splitting the quadrant when there are two such particles, this just adds each particle to an unordered list of NCHILD particles under the node. When the list is full, we create a layer of 8 child nodes and re-add the particles. This ensures that child nodes are close together, and it means that tree moment building doesn't have a hard-to-predict branch in it (each node either has nodes as children or particles). …
> Newtreebuild

- Options.mk.example
- README.rst
- gadget/main.c
- libgadget/allvars.h
- libgadget/drift.c
- libgadget/forcetree.c
- libgadget/utils/spinlocks.c
- libgadget/utils/spinlocks.h
- platform-options/Options.mk.macos
I found that using OMP locks slows down the tree build by a factor of 200 (!) so that it now takes 85% of the simulation runtime. This only seems to happen on intel, so it affects stampede and frontera. About 60% of the time was spent in init_spinlocks, 30% spent in creating the nodes. This might be a bug with intel's openmp implementation, or it might be because it is using mutexes instead of spinlocks. godbolt suggests that icc does produce much longer code for init_spinlocks than gcc 
In any case, revert this because it is not worth the effort to root cause.
@rainwoodman : Any better ideas for this?
> Revert "Merge pull request #323 from sbird/nopthread"

- libgadget/gravshort-tree.c
which does not take account of periodic boundary conditions, first discovered by 1907.03542.
In Illustris, Eagle, and IllustrisTNG there is a small number of galaxies with very low DM fraction
located directly at a boundary of the periodic box (but not the same boundary).
This flawed dynamics arises from an unlucky and rare combination of factors.
The dense stellar core experiences an unusually large force error because to compute the tree force
from material on the opposite side of the box a very large tree node is used.
This is deemed allowed by the code because the total accelerations within the dense stellar core are
quite large, so the estimated contribution to the relative error is small even for this large node.
However, this error is severely underestimated by the code in this …
> Fix a bug in the force tree opening criteria

- libgadget/blackhole.c
- libgadget/petaio.c
- libgadget/slotsmanager.c
- libgadget/timebinmgr.c
This is a minimal fix for the black hole drifting (and a couple of other memory bugs!). The drifting was broken because MinPotPos was being over-written with the current position after being set to the potential minimum. This PR should definitely be merged.
> Minimalfixbhdrift

- libgadget/blackhole.c
- libgadget/hydra.c
- libgadget/hydra.h
- libgadget/init.c
- libgadget/slotsmanager.h
- libgadget/timestep.c
This removes some unloved parts of the black hole code. The major change is to the black hole timestepping: instead of the BH timestep being <= the smallest SPH timestep surrounding it, it is now = the smallest SPH timestep. This avoids situations where the smallest timesteps contain exclusively black holes.
> Black hole cleanups

- libgadget/blackhole.c
- libgadget/forcetree.c
- libgadget/timestep.c
- libgadget/treewalk.c
This PR: 
1) Makes it easier to debug a failure of the force tree to build
2) Makes the first stage of the force tree building non-recursive, so that we don't have a stack overflow if multiple particles are in the same spot.
3) Removes the sound speed check for the black hole mergers. This is actually a very bad idea, but we never noticed before because with repositioning broken there were no mergers anyway!
What happens goes like this:
1. BH moves to halo center
2. Merger happens
3. N+1 BHs move to halo
4. These BHs have different velocities so fail the sound speed check and do not merge. They are not dissipative so have no way for the velocities to reduce.
if N < 11:
Goto 1.
if N > 11:
Too many particles in one place for the tree to build!
goto 5.
5. The function which creates new tree …
> Fix black holes and the tree

- blackhole.c
This was a bad idea, because the black holes are repositioned, but their
velocities are not zeroed, and they are not dissipative.
Over time it will create a clump of black holes at identical positions
in the center of the halo, unable to merge. This will very
much slow down the code.
This is the BT equivalent to PR #336
> Remove the black hole velocity check on mergers

- libgadget/exchange.c
It was taking too much of the total time.
It is most often during a full domain decomp anyway, when the peano sort will remove the particles just afterwards. A particle table full of garbage does slow down the tree a little (~1%), but this is small compared to the cost of garbage collection, which was > 30% on the same run.
> Don't do a small GC on large particle exchanges

- gadget/params.c
- libgadget/allvars.h
- libgadget/drift.c
- libgadget/drift.h
- libgadget/init.c
- libgadget/petaio.c
- libgadget/run.c
This shifts the periodic box by a smallish random number to avoid inter-timestep correlations in the tree opening condition. The public Arepo release does something similar, but we use a much smaller shift so we don't move transfer all particles between processors every full domain decomp. This appears to actually increase speed slightly (!) by reducing the short range gravity time but I suspect this of being a coincidence in this specific box.
> Add a random offset to particle positions, changing every PM step

- gadget/params.c
- libgadget/allvars.h
- libgadget/checkpoint.c
- libgadget/fofpetaio.c
- libgadget/init.c
- libgadget/petaio.c
- libgadget/petaio.h
- libgadget/runtests.c
- libgadget/timebinmgr.c
- libgadget/timestep.c
- libgadget/timestep.h
This PR saves a variety of extra fields (all fields in P and SPHP) to the crash dump snapshot, and optionally to the main snapshot. It also saves and restores DelayTime, which we weren't doing before. This should be enough to debug future "bad timestep" crashes.
> Debugoutput

- libgadget/petaio.c
I forgot to do this before. Fix the box wrapping on the particle offsets so the output lies within the box.
> Ensure proper box wrapping for particle offset outputs

- gadget/main.c
- gadget/params.c
- genic/main.c
- libgadget/allvars.h
- libgadget/utils/endrun.c
- libgadget/utils/endrun.h
- tests/stub.c
Printing the backtrace hangs on stampede (in the fork() call). I can't see that we can do anything about this, so add an option to disable backtrace printing
> Option to disable stack trace

- gadget/main.c
- genic/main.c
On the recommendation of one of the Stampede admins
I think this will have little effect, because it seems most implementations are only affected if you use  MPI_THREAD_MULTIPLE, and their support is flaky at best, but it can't hurt.
> Use MPI_Init_thread instead of MPI_Init

- libgadget/allvars.h
- libgadget/blackhole.c
- libgadget/domain.c
- libgadget/exchange.c
- libgadget/exchange.h
- libgadget/fof.c
- libgadget/fofpetaio.c
- libgadget/init.c
- libgadget/partmanager.h
- libgadget/petaio.c
- libgadget/petaio.h
- libgadget/petapm.c
- libgadget/run.c
- libgadget/runtests.c
- libgadget/sfr_eff.c
- libgadget/sfr_eff.h
- libgadget/tests/test_exchange.c
- libgadget/utils/mpsort.c
- libgadget/utils/openmpsort.c
- libgadget/utils/system.h
The point of this PR is to avoid the double particle exchange when saving a FOF table. Instead it makes a copy of the subset of the particles in the halos, exchanges them to the right processor, saves and discards them. This has the side-effect that a FOF table save does not affect the overall particle order. To do this I had to add a lot of infrastructure to make the particle and slot tables local to their functions in the IO and exchange routines. This was enough effort that I am probably not making these fully local variables any time soon. There was also a lot of messing about with the semi-generic IO routines, which is a little ugly.
What do you think? The IO routine stuff badly needs cleaning up, but I am unsure how to do that without going full C++.
> Avoid FOF double exchange

- .gitmodules
- libgadget/domain.c
- libgadget/slotsmanager.c
This PR force-disables gather sort in MP-Sort, which has problems with icc, and by default doesn't use MP-Sort during the domain decomposition. It also modifies domain so it handles uneven particle distributions with garbage better.
> Noglobalsort

- libgadget/fof.c
The HEAD() function is called from a threaded context, and not protected
by locks (unlike HEADl()), so we can't change the head particle inside
it. The trees should still be short because we call update_root inside
HEADl while protected by a lock. Hopefully this fixes the pesky deadlock
on stampede.
> Remove FOF splay from unlocked HEAD function

- libgadget/utils/system.c
- libgadget/utils/system.h
This will detect when the MPI library is incorrectly returning zeros
from collective calls. Checked are MPI_INT, MPI_DOUBLE and MPI_LONG,
with MPI_MIN and MPI_MAX.
> Add checked version of MPI_Allreduce and MPI_Reduce

- examples/heliumreion/paramfile.gadget
- examples/hydro/paramfile.gadget
- examples/small/paramfile.gadget
- examples/travis/paramfile.gadget
- libgadget/blackhole.c
- libgadget/density.c
- libgadget/fof.c
- libgadget/sfr_eff.c
- libgadget/timebinmgr.c
- libgadget/timestep.c
- libgadget/winds.c
The only really important commit is 2bb1165 which changes the wind model to be less timing dependent: this should help the code give more similar answers in threaded mode vs. non-threaded mode for the hydro run. It does this by allowing particles to be made wind twice. Also switch some of the examples to isotropic winds, which modern practice shows is simpler and somewhat cleaner.
> Windmodelfix

- libgadget/domain.c
- libgadget/exchange.c
- libgadget/exchange.h
- libgadget/fofpetaio.c
- libgadget/run.c
- libgadget/sfr_eff.c
- libgadget/tests/test_exchange.c
- Limits the exchange to 2GB, to make MPI on Frontera happy
- Limits the BH heating to 10^8 K to make the timestepping happier
- Fixes multiple exchange iterations
- Enforces that fof petaio cannot do multiple iterations (it is not implemented).
> Exchangefix

- libgadget/blackhole.c
- libgadget/winds.c
This is attempt 2 at removing the spinlocks. It is documented to work (unless I have made a bug). It is a compare exchange algorithm which will work best when the memory is uncontended (often for us). Technically it is a gcc extension (from v 5) but it looks like icc and clang both support it on the versions that we care about. If we find a compiler that doesn't support it, I may back this out.
> Nospinlocks

- libgadget/run.c
- libgadget/timestep.c
Simple fix: avoid the check on init.
> Fix a floating point roundoff crash when resuming from some snapshots

- README.rst
- gadget/main.c
- libgadget/utils/spinlocks.c
- platform-options/Options.mk.macos
Selected by the compile flag and enabled for Mac. It is slower but for
Mac that will be ok.
> Provide an alternative, non-pthread spinlock implementation.

- gadget/params.c
- libgadget/allvars.h
- libgadget/density.c
- libgadget/forcetree.c
- libgadget/forcetree.h
- libgadget/gravity.h
- libgadget/gravshort-pair.c
- libgadget/gravshort-tree.c
- libgadget/gravshort.h
- libgadget/init.c
- libgadget/partmanager.c
- libgadget/partmanager.h
- libgadget/run.c
- libgadget/tests/test_density.c
- libgadget/tests/test_forcetree.c
- libgadget/tests/test_gravity.c
- libgadget/timestep.c
Cleanup the force softening code and remove a parameter from the Node structure. This removes the ability to have different softening parameters for different particle types, which is probably a bad idea from the point of view of force accuracy.
> Softeningcleanup

- libgadget/run.c
This is done so the error estimate is consistent. This was
always a small effect, I think, and has become much smaller since we
started randomising the particle positions after every domain.
So save us some time on startup.
> Remove the extra tree evaluation on the first step

- libgadget/blackhole.c
- libgadget/run.c
- libgadget/sfr_eff.c
- libgadget/slotsmanager.c
- libgadget/slotsmanager.h
This PR follows upstream Gadget-3 and Arepo in computing the cooling and BH operators after the kicks. It is the recommended way of permanently solving the short timestep problem, because the cooling and BH operators now happen at a consistent time and do not affect DtEntropy (so the predicted entropy in hydra is not off), rather changing Entropy directly.
> Cooling strang split

- libgadget/domain.c
The error is:
[ 000370.59 ] Task 0: toptree[162].Count=1, shift 0, last_leaf=162 key = 6020610249 i= 16 Nsample = 2563717
The assert is to avoid us encountering an already processed node, but the crash is actually a valid case:
we could not refine the node further, as shift was already zero. So we can just continue.
> Potential fix for #429

- libgadget/forcetree.c
- libgadget/tests/test_forcetree.c
I noticed in a profile that the forcetree moment calculation time was dominated by the memory access of the particles. In the node build this is already inside cache. This computes the lowest order moments inside the node build, thus speeding up moment calculation by a factor of about 2.
Some numbers: 
master:
[ 000000.00 ] [ RUN      ] test_rebuild_flat
[ 000000.13 ] Allocated 280 MByte for 2097152 tree nodes. firstnode 2097152. (presently allocated 296.004 MB)
Number of nodes used: 374785. Built tree in 20.3 ms
Tree filling factor: 0.501983 on 373881 nodes (wasted: 904 empty: 0)
Updated moments in 15.1 ms. Total mass: 2.09715e+06
[ 000000.89 ] [       OK ] test_rebuild_flat
[ 000000.89 ] [ RUN      ] test_rebuild_close
[ 000001.03 ] Allocated 280 MByte for 2097152 tree nodes. firstnode …
> Forcetree moments

- libgadget/treewalk.c
- libgadget/treewalk.h
ce3e0e2a84:
Replace final alloca calls in treewalk
Use instead allocations on the ta malloc heap. This removes a
substantial source of thread-local stack allocations.
Removed thread-local stack allocations. This had no effect on a pure
MPI run but costs us a factor of 2 (!) in threaded performance, making
the threaded code half as fast as the MPI code.
I am not sure why this is. I suspect it may be that the stack variable
can be optimized out entirely by the compiler, but the heap variable
cannot. It may also be some effect of the processor caches.
> Revert ce3e0e2a84 due to major performance loss for threaded code.

- libgadget/fof.c
- libgadget/treewalk.c
This PR cleans up the locking in the FoF code. I noticed there was a catastrophic performance dropoff when we switched to dynamic treewalking, because particles in the same halos were on different threads and there was massive contention. This fixes it by moving to a lockless algorithm and by increasing the chunk size. Also fix a locking bug in the secondary treewalk.
> Use compare exchange in the FoF code

- libgadget/checkpoint.c
- libgadget/checkpoint.h
- libgadget/run.c
Fixes: #453
Also ensures that the GroupID in the particle tables is up to date by
moving fof before checkpoint. write_checkpoint now only writes the
checkpoint, not the fof.
> Ensure tree is allocated before generating FOF tables for checkpoint.

- libgadget/blackhole.c
- libgadget/petaio.c
- libgadget/run.c
- libgadget/slotsmanager.h
When doing the power law seeding, we might need to log the seed mass for each black hole (e.g. when calculating the faint end population we might only want to account for the BH accretes well beyond the seed mass).  We can also extract this information from BlackholeDetail history, but that's a lot of work when we have tons of BHs.
I also want to append the RestartSnapNum to BlackholeDetail file, otherwise the binary file would be huge (and sometimes be re-written) and would be hard to post process.
> Log Mseed for blackholes and append SnapNum to BlackholeDetail file

- libgadget/hci.c
- libgadget/hci.h
- libgadget/run.c
- libgadget/tests/test_hci.c
So that auto generated PART_ snapshots have a PIG_ with them.
> Write a FOF table with an auto checkpoint if FOF is enabled

- libgadget/forcetree.c
- libgadget/tests/test_forcetree.c
This should help the parallelization of the tree moment calculation by
ensuring that each task has real particles to compute and is roughly
equal in depth.
> Start the recursive treebuild from the leaf topnodes

- libgadget/fof.c
Should speed up fof secondary nearest neighbours: no need to search further than the neighbour we already found.
> Short-circuit the fof secondary NN search

- gadget/params.c
- libgadget/allvars.h
- libgadget/density.c
- libgadget/domain.c
- libgadget/exchange.c
- libgadget/forcetree.c
- libgadget/forcetree.h
- libgadget/init.c
- libgadget/petaio.c
- libgadget/run.c
- libgadget/tests/test_forcetree.c
- libgadget/utils/event.c
This branch uses a lockless algorithm for the tree build. On N threads it builds N subtrees and then merges them. Each topnode is merged separately, so that there is some parallelism in the merge step (not that much, but it does not appear to be the dominant step). This scales much better with threads and is also a little faster.
> Mapreduceforcetree

- libgadget/fof.c
- libgadget/metal_return.c
- libgadget/treewalk.c
- libgadget/treewalk.h
This is the latest attempt to improve the balance of the stellar density (metal return) code. If this works we could perhaps use it for the gas density as well. The idea is that to use that computing the neighbour number, NumNgb, for any smoothing length h < H (where H is the current particle Hsml) is essentially free, because the treewalk is dominated by the memory latency involved in fetching the nodes and particles. So we can compute NumNgb(h_i) for multiple h_i values in parallel and use this information to efficiently bound the desired SPH smoothing length. This dramatically reduces the maximum number of density iterations, from about 10 to 3. This should also improve the balance as the final iterations usually have very few particles active.
A side effect is that we can stop a …
> Do multiple density iterations at once

- libgadget/Makefile
- libgadget/domain.c
- libgadget/domain.h
- libgadget/drift.c
- libgadget/drift.h
- libgadget/exchange.c
- libgadget/exchange.h
- libgadget/fofpetaio.c
- libgadget/run.c
- libgadget/tests/test_exchange.c
This combines drifting with domain exchanging. Since in practice both are loops over all particles and dominated by the memory latency, doing both at once is basically the same cost as the longest one. Zero change to output, some moderate speed-up on a small simulation.
> Combineddrift

- libgadget/density.c
- libgadget/drift.c
- libgadget/drift.h
- libgadget/exchange.c
- libgadget/hydra.c
- libgadget/partmanager.h
- libgadget/run.c
- libgadget/timestep.c
- libgadget/timestep.h
This PR improves the estimation of h and rho for inactive particles to the drifting formula used in Gadget-4. 
We currently use the formula from Gadget-2, which is pathologically wrong for really deep timesteps because the exp() runs away. For this reason the formula is disabled in most places and we use the Density at the last active time for the particle. This is the same equation implemented, only a more accurate solution to it. It only affects the hydro (although it would affect other symmetric tree walks if we had any) and should improve force estimation moderately.
> Driftdensity

- libgadget/density.c
- libgadget/treewalk.c
- libgadget/treewalk.h
This ensures that the ReDoQueue only needs be as large as the workset,
which is for density 1/2 of the total particles.
Memory optimization
> Run treewalk_build in treewalk_do_hsml_loop before treewalk_run

- libgadget/treewalk.c
If the buffer fills up exactly on the end of a chunk, we don't need to
remove the final partially exported particle, because it is actually
fully exported. Also make the BufferFullFlag atomic to avoid a
(technical) data race.
> Fix an edge case with treewalk buffer fillup

- libgadget/blackhole.c
- libgadget/density.c
- libgadget/timebinmgr.c
- libgadget/winds.c
Exclude wind particles from the BH density, to match the accretion treewalk, where they are excluded.
> Exclude wind from BH density

- libgadget/exchange.c
- libgadget/fofpetaio.c
- libgadget/partmanager.h
- libgadget/run.c
- libgadget/utils/system.c
The first fix to allow multiple iterations during fof particle exchange was too slow. This fix is faster and allows the exchange code to handle resumability, instead of the fof code, at the cost of a slight hack in the particle data structure.
Also some debugging and robustness changes to the exchange code in an attempt to work out why large exchanges sometimes fail.
> Fofexchangefix2

- libgadget/cooling_qso_lightup.c
The check for HeII reionization happening was in
during_helium_reionization and included a check for the redshift being
low enough to flash-ionize. But that is still helium reionization! As
the code was not during helium reionization, this meant that the flash
ionization never happened.
A side consequence is that the long mean free path heating was being added 
even after HeII reionization completed for some particles.
> Fix flash ionization at end of HeII reionization.

- libgadget/blackhole.c
- libgadget/cooling_qso_lightup.c
- libgadget/hydra.c
- libgadget/hydra.h
- libgadget/petaio.c
- libgadget/sfr_eff.c
- libgadget/stats.c
- libgadget/timestep.c
- libgadget/winds.c
Change various uses of the energy weighted density as a conversion factor between entropy and internal energy to use the regular density, which is the more correct conservative quantity. This may be affecting the adiabatic cooling at late times.
> Fixtempconverge

- libgadget/gravshort-tree.c
Prior to this commit, adaptive softenings would blindly walk the tree to
the first child of the node if the opening condition was met. This
was bad if the node opened was a leaf node. The refactor fixes this
condition.
Fixes: #562
> Fix hang with adaptive softenings

- libgadget/petaio.c
- libgadget/run.c
by moving the IOTable closer to the file read
> Fix an out-of-order memory free when neutrinos are on

- libgadget/blackhole.c
apply gravitational bound check only when reposition is disabled, to prevent the issue when two BHs repositioned to the same location but unmerged.
> fix MergeGravBound

- gadget/params.c
- libgadget/blackhole.c
- libgadget/metal_return.c
We just noticed it was buggy: the accretion uses the BH Hsml, the feedback uses the FeedbackRadius, but the treewalk is only computed out to FeedbackRadius, so there may not be any particles inside the kernel.
> Remove explicitly setting the BH feedback radius.

- .github/workflows/main.yaml
- maintainer/conda-env.yaml
Pin gcc to 9.3.0, last good version.
Refer to https://github.com/AnacondaRecipes/mpich-feedstock/issues/5
> workaround anaconda mpicc/gcc incompatibility.

- libgadget/treewalk.c
The error is:
[ 059851.77 ] ERROR: Task 673: Something screwed up in export queue: nexp 1272278 (local 2) last 79115500 != index 79115499
This happens when lastreal (the last element in the workqueue
which was evaluated) is larger than the last element in the export
buffer. But that is actually fine: there can be particles with no
exports. Weaken the condition to allow for this.
> Fix spurious rare export buffer full crash:

- libgadget/fofpetaio.c
Reduce peak memory usage while saving FOF particles. Some slightly sneaky things are being done here, but they seem to work.
> Fofsaveparticlememreduce

- libgadget/blackhole.c
- libgadget/blackhole.h
- libgadget/density.c
- libgadget/density.h
- libgadget/hydra.c
- libgadget/petaio.c
- libgadget/run.c
- libgadget/sfr_eff.c
- libgadget/sfr_eff.h
- libgadget/slotsmanager.h
- libgadget/winds.c
- libgadget/winds.h
Separate the velocity dispersion calculation from the rest of the winds and only run it on PM steps. This produces about the same result in a small simulation (and is what Illustris did) but it means we do not have to build a tree with DM particles for winds on short timesteps.
> Separatevdisp

- libgadget/timestep.c
The code for handling the special case where all the active gas particles had formed stars looks through all stars, rather than all recently formed stars, and was incorrectly not collective.
Fix this. Thanks to Nishikanta Khandai <nkhandai@niser.ac.in> for the bug report.
> Fix a timestep bug

- libgadget/blackhole.c
- libgadget/exchange.c
- libgadget/slotsmanager.c
- libgadget/slotsmanager.h
@yueyingn What do you think of this? It makes every sph_particle_data and every star_particle_data 64-bits smaller, but it removes a check in the exchange code that has caught bugs before (although I think not bugs in production). Living dangerously but likely reduces memory use noticeably.
> Remove 64-bit debug variable unless DEBUG is on

- libgadget/forcetree.c
- libgadget/forcetree.h
- libgadget/tests/test_forcetree.c
Some attempts to debug a bus error on Frontera with ASTRID.
Here is the error:
[ 098868.09 ] Forces computed.
[ 098868.09 ] Hydro timesteps: Accel: 0 Soundspeed: 119 DivVel: 0 Accrete: 0 Neighbour: 0
[ 098868.09 ] Min grav timebin: 12 mintimebin 5
[ 098868.33 ] domain decomposition... (presently allocated=27148.1 MB)
[ 098868.33 ] Allocated 1611.5 MByte for top-level domain structure
[ 098868.33 ] Attempting new domain decomposition policy: TopNodeAllocFactor=0.5, UseglobalSort=1, SubSampleDistance=16 UsePreSort=0
[ 098868.61 ] use of 2014.33 MB of temporary storage for domain decomposition... (presently allocated=30758.4 MB)
[ 098869.57 ] local topTree size before appending=523545
[ 098869.58 ] Final local topTree size = 527961 per segment = 4.60345.
[ 098869.59 ] NTopLeaves= 461966 …
> Fix SIGBUS

- libgadget/Makefile
- libgadget/bhinfo.c
- libgadget/bhinfo.h
- libgadget/bhmerger.c
- libgadget/bhmerger.h
- libgadget/blackhole.c
- libgadget/blackhole.h
- libgadget/cooling_qso_lightup.c
- libgadget/cooling_qso_lightup.h
- libgadget/forcetree.c
- libgadget/metal_return.c
- libgadget/metal_return.h
- libgadget/run.c
An addition to separate tree. Split the BH mergers into a separate file, using a separate treewalk.
Make a single tree containing only gas particles at the start of the timestep, and reuse it throughout the timestep. It no longer contains black holes. This lets the density and hydro code be a little faster again, and it avoids the need to rebuild the gas tree at all.
Splitting the BH mergers into a separate treewalk ensures that accretion is handled before mergers. This is mostly because to make the code faster. There are edge cases where the code behaviour depends on whether the gas or BH accretes first, but I have thought about it and believe that these only occur because we do not conserve momentum on accretion until bhbugfixes is merged.
> Sepbhmerger

- examples/dynfric/paramfile.gadget
- examples/dynfric/paramfile.genic
- examples/dynfric/run.sh
- examples/hydro/paramfile.gadget
- libgadget/blackhole.c
- libgadget/blackhole.h
- libgadget/forcetree.c
- libgadget/gravity.h
- libgadget/gravpm.c
- libgadget/run.c
- libgadget/runtests.c
- libgadget/tests/test_forcetree.c
- libgadget/tests/test_gravity.c
- libgadget/treewalk.c
This fixes some clear (but small effect) bugs in the BH module.
To Black hole mergers:
- Make the BH treewalk symmetric again, so that we check if either BH is close to the other one. Only matters if the BH Hsml is < 2 * Force softening.
- Ensure that the SwallowID does not persist over timesteps. This ensures that black holes which are marked but not swallowed (because the swallowing BH is swallowed first) are not prevented from merging in future timesteps. This should be rare (as the comment said), but is worth fixing.
- We avoid two BHs trying to swallow each other (ie, break the symmetry) by checking that a black hole only merges another with a larger ID. But only active black holes can swallow, so this can prevent an inactive black hole from being merged. This again is a rare case, …
> Bhbugfixes

- examples/dynfric/paramfile.gadget
- examples/dynfric/paramfile.genic
- examples/hydro/paramfile.gadget
- gadget/main.c
- libgadget/bhdynfric.c
- libgadget/bhdynfric.h
- libgadget/bhinfo.c
- libgadget/blackhole.c
- libgadget/blackhole.h
- libgadget/cooling_qso_lightup.c
- libgadget/cooling_qso_lightup.h
- libgadget/density.c
- libgadget/drift.c
- libgadget/forcetree.c
- libgadget/forcetree.h
- libgadget/gravshort-pair.c
- libgadget/hydra.c
- libgadget/metal_return.c
- libgadget/metal_return.h
- libgadget/run.c
- libgadget/treewalk.c
This lets DF use a separate, star-only, tree. The minimum potential computation uses the same tree.
The idea here is that accretion and feedback now use a gas only tree, and so the treewalks are faster.
> Separatetree

- gadget/params.c
- libgadget/sfr_eff.c
Add option to reduce SF timescale for ultra dense gas with density above certain factor of the SF threshold. TNG50 uses BoostSFOverDenseFactor=230
> Reduced SF timescale 

- libgadget/Makefile
- libgadget/forcetree.c
- libgadget/tests/test_peano.c
- libgadget/utils/peano.c
- libgadget/utils/peano.h
Add a test of the Peano curve calculator and do some micro-optimisations with godbolt. Speeds up the timing test from 50 ms to 36 ms on my desktop. Commit 0a353b4c6c7 goes from 37.6 ms to 36, which is small but not nothing.
> Fasterpeano

- libgadget/forcetree.c
- libgadget/forcetree.h
- libgadget/gravshort-pair.c
- libgadget/gravshort-tree.c
- libgadget/gravshort.h
- libgadget/run.c
- libgadget/treewalk.h
This should fix the asynchronous treewalk gravity problem when the exchange buffer fills up. As a bonus fix the problem where the potential was not updated every PM step and a bug in the density test.
> Fixasynctreefullbuffergravity

- Options.mk.example
- README.rst
- libgadget/utils/system.c
- platform-options/Options.mk.BlueTides
- platform-options/Options.mk.cori
- platform-options/Options.mk.coriknl
- platform-options/Options.mk.edison
- platform-options/Options.mk.example.coma
- platform-options/Options.mk.example.icc
- platform-options/Options.mk.frontera
- platform-options/Options.mk.macos
- platform-options/Options.mk.pfe
- platform-options/Options.mk.scanbuild
- platform-options/Options.mk.travis
because if Isend/Irecv don't work we now have big problems! We use it exclusively in treewalk.
> Remove NO_ISEND_IRECV_IN_DOMAIN 

- gadget/params.c
- libgadget/domain.c
- libgadget/treewalk.c
1. change the ImportBufferBoost to be a float parameter 
2. make DomainOverDecompositionFactor half of the available threads, so there are fewer export particles
> fix the memory issue of export/import 

- Makefile.rules
- gadget/Makefile
- genic/Makefile
- libgadget/Makefile
- libgenic/Makefile
Uses -MMD to generate .d files and loads them into make.
> Replace the manual list of headers with an autogenerated dependency list

- libgadget/treewalk.c
- libgadget/utils/openmpsort.c
- libgadget/utils/system.c
- libgadget/utils/system.h
The standard does not guarantee that the merges are atomic, it seems. This new code seems to improve memory safety even on intel, so let's make it unconditional. It will make the sort a bit slower but we can live with that.
> Fix the OpenMP sort on ARM architectures.

- libgadget/treewalk.c
We need to cast the results of `mymalloc` otherwise it's a value of type `void *` and cannot be assigned to other variables. This is only a problem when we use a `C++` compiler.
> Cast the results of malloc otherwise the C++ compiler fails.

- genic/main.c
- libgenic/power.c
- libgenic/tests/test_power.c
Give an error message if the gap is too large. Assume the power spectrum is constant if a small distance past the table.
> Improved handling if the power spectrum table is too short

- libgadget/forcetree.c
In the omp task in forcetree_recursive, we had some shared variables. However, these variables could all be made const. Once this happens they can be moved to firstprivate because the compiler can optimise them away and avoid using new stack space. The shared clause can go away.
This also means that we no longer fail to compile on old gcc that has default shared openmp variables!
Thanks to Asher Sang for the suggestion.
> Make shared omp variables const and move to firstprivate

- libgenic/power.c
- libgenic/tests/test_power.c
This means that MP-GenIC produces an initial baryon velocity similar to the CDM velocity, when it should be much smaller!
Reported-by: Matt McQuinn <mcquinn@uw.edu>
> Fix a missing factor of aH / c in the baryon velocity transfer function

- tools/plot-structure.py
This PR corrects a data type issue in plot-structure.py where the extent argument passed to plt.imshow() could include NumPy arrays instead of floats, causing rendering errors. Now the box size is explicitly cast to a float when needed. Comments and cleanup have also been added for clarity.
> Fix for bug in plot-structure.py extent handling
