Makefile.rules
allvars.h
forcetree.c
forcetree.h
gravpm.c
gravshort-pair.c
gravshort-tree-old.c
gravshort-tree.c
init.c
longrange.c
main.c
param.c
petapm.c
proto.h
run.c
timestep.c

Some cleanups
- Fixes to the power spectrum normalisation
- Make sure power is output simultaneously to the snapshot

Cleanups and fixes to the power spectrum

---

domain.c
proto.h
system.c

Fixes to code before restarting BT2.

Restart fixes

---

examples/lya/paramfile.gadget
fofpetaio.c
init.c
petaio.c
petaio.h
run.c

This remove the requirement that particles must be sorted by type before IO.

Remove requirement particles sorted by type before IO

---

Makefile.tests
allvars.h
domain.c
domain.h
forcetree.c
forcetree.h
gravpm.c
gravshort-tree-old.c
gravshort-tree.c
gravshort.h
init.c
param.c
tests/stub.c
tests/test_forcetree.c
timestep.c
treewalk.c

Filing a PR, such that it is easier to compare the difference.

WIP: Forcetree test

---

begrun.c
io.c
main.c
proto.h

The snapshot number is recorded in a simpler file Snapshots.txt

Recover from the last snapshot in mode 1.

---

allvars.h
init.c
io.c
petaio.c
run.c
tests/test_timebinmgr.c
timebinmgr.c
timestep.c
timestep.h

This is something I've been meaning to do for a while, but the arbitrary syncpoints make it easy.

Integer Timeline doesn't change over an unscheduled save/resume

---

domain.c

print a warning when they disagree too strongly with each other.
Intended to fix #141

Allow merging deeperly diverged subtrees in domain.

---

examples/dm-only/paramfile.gadget
examples/lya/paramfile.gadget

I modified the configuration files in examples/lya and examples/dm-only to work well with the new softening settings and WindOn option.
Also, I commented out the BlackHole options from the configuration files, although I'm not sure this is the right thing to do... Do you expect most people to compile the code with the BlackHole option? 
PS: this is also my first attempt to merge from a fork, I hope I don't break the whole internet.

updated lya config files after changes in softening and winds

---

examples/travis/paramfile.gadget
gravshort.h
petaio.c

This should fix #125. Do you see problems Ananth?

Add gravity to BH, and save drifting position in snapshots.

---

allvars.h
param.c

Following the discussion around issue #150 . Please review!

drop guards around BlackHoleFeedbackMethod

---

domain.c

This fixes a memory leak in domain_check_memory_bound and should fix Issue 172.

Fixmemleak

---

Makefile.rules
domain.c
exchange.c
param.c
slotsmanager.c

This was causing problems with icc for me. Found with gcc's undefined behaviour sanitizer.

Fix some undefined behaviour

---

slotsmanager.c
tests/test_slotsmanager.c

Should fix #171 !
Also fix slots_reserve when system malloc is being used (and thus the base pointer realloced changes).

Fix some edge conditions in the slotsmanager

---

begrun.c
predict.c

Take a look if this will help?

Bt ii early jump

---

Makefile.rules
blackhole.c
density.c
hydra.c
timestep.c
timestep.h

Fix some compile warnings when LOW_PRECISION=float and make everything depend on Makefile.rules . Nothing important.

Small fixes

---

.travis.yml
fof.c
genic/main.c
genic/power.c
genic/proto.h
genic/save.c
sfr_eff.c

Two trivial fixes for pure particle neutrinos. These have no effect if you are using the linear response neutrinos, which @andreufont is.

Fixes for particle neutrinos

---

examples/linear_growth/paramfile.gadget
examples/neutrinos/paramfile.gadget
gadget/params.c
genic/params.c
libgadget/domain.c
libgadget/fof.c
libgadget/treewalk.c
tools/make_class_power.py

Now I merged the newer neutrino code, remove the obsolete parameters from the paramfile.
Also fix some whitespace and a (spurious) compiler warning.

Small fixes following the neutrino merge

---

libgadget/exchange.c

Fix for icc bug when using -march=native optimisation

---

gadget/main.c
libgadget/checkpoint.c
libgadget/cosmology.c
libgadget/gravpm.c
libgadget/neutrinos_lra.c
libgadget/neutrinos_lra.h
libgadget/omega_nu_single.c
libgadget/omega_nu_single.h
libgadget/powerspectrum.c
libgadget/powerspectrum.h
libgadget/run.c
libgadget/tests/test_neutrinos_lra.c
libgadget/tests/test_omega_nu_single.c
libgadget/timestep.c
libgenic/power.c
libgenic/tests/test_power.c
libgenic/zeldovich.c
tools/make_class_power.py

This pull request fixes some edge cases in the neutrino code to do with memory allocation, quiets some debugging information and frees the powerspectrum memory after a PM step.

Fixes to neutrino code

---

libgadget/petaio.c

This brings some speed improvements recently found from FastPM.

Update mpsort and bigfile to latest upstream.

---

examples/glass/paramfile.genic
examples/glass/run.sh
gadget/params.c
genic/main.c
genic/params.c
libgadget/gravpm.c
libgadget/neutrinos_lra.c
libgadget/neutrinos_lra.h
libgadget/powerspectrum.c
libgadget/powerspectrum.h
libgadget/timestep.c
libgenic/Makefile
libgenic/allvars.h
libgenic/glass.c
libgenic/proto.h
libgenic/zeldovich.c

This PR adds a glass generator to MP-GenIC.
Instead of reading from a file, it solves the glass relaxation problem on the full grid.
It is a bit slow -- requires about 15 PM steps per species. 
We can perhaps add the number of glass steps as a parameter.

Add a glass initial condition generator to MP-GenIC.

---

genic/params.c
libgenic/power.h
tools/make_class_power.py

Added PrimordialRunning to MP-GenIC and make_class_power.py

---

libgadget/density.c

A few cosmetic cleanups in the Density code.

Densityclarify

---

libgadget/domain.c
libgadget/exchange.c

Fix Issue #261 by checking for garbage, and a potential issue where domain leaves no space for star formation.

Exchangegcfix

---

examples/hydro/paramfile.genic
gadget/main.c
libgadget/domain.c
libgadget/domain.h
libgadget/exchange.c
libgadget/exchange.h
libgadget/fofpetaio.c
libgadget/forcetree.c
libgadget/forcetree.h
libgadget/gravpm.c
libgadget/init.c
libgadget/run.c
libgadget/run.h
libgadget/runtests.c
libgadget/sfr_eff.c
libgadget/tests/test_exchange.c
libgadget/tests/test_forcetree.c
libgadget/treewalk.c

This is the equivalent to the ModularTree PR but for domain. Again tested it makes no difference to output.

Modulardomain

---

examples/travis/check-results.py
genic/main.c
genic/params.c
libgenic/allvars.h
libgenic/glass.c
libgenic/proto.h
libgenic/save.c
libgenic/zeldovich.c

Some changes to the glass file generation to better implement matching linear growth functions.

Yetmoreglass

---

gadget/params.c
libgadget/allvars.h
libgadget/domain.c
libgadget/domain.h
libgadget/exchange.c
libgadget/exchange.h
libgadget/fofpetaio.c
libgadget/forcetree.c
libgadget/forcetree.h
libgadget/init.c
libgadget/partmanager.h
libgadget/run.c
libgadget/runtests.c
libgadget/tests/test_exchange.c
libgadget/tests/test_forcetree.c

This is a cleanup branch which makes domain and tree global parameters local to each module.

Localparams

---

gadget/main.c
gadget/params.c
genic/main.c
libgadget/allvars.c
libgadget/allvars.h
libgadget/blackhole.c
libgadget/blackhole.h
libgadget/checkpoint.c
libgadget/density.c
libgadget/fof.c
libgadget/fof.h
libgadget/fofpetaio.c
libgadget/hydra.c
libgadget/init.c
libgadget/petaio.c
libgadget/petaio.h
libgadget/run.c
libgadget/runtests.c
libgadget/sfr_eff.c
libgadget/sfr_eff.h
libgadget/treewalk.c
libgadget/treewalk.h
libgadget/winds.c
libgadget/winds.h

Do the same localisation of parameters from domain and forcetree to winds, sfr and blackhole.
This was pretty easy. The only tricky part was moving the wind-related code scattered around the place into the winds module.

Localwindparams

---

README.rst

Fix some of the urls and explain compile options better.

Clarify and update parts of README.rst

---

libgadget/blackhole.c
libgadget/domain.c
libgadget/fof.c
libgadget/fofpetaio.c
libgadget/forcetree.c
libgadget/gravshort-tree.c
libgadget/init.c
libgadget/petapm.c
libgadget/run.c
libgadget/sfr_eff.c
libgadget/utils/endrun.c
libgadget/utils/system.c
libgadget/utils/system.h
libgenic/zeldovich.c

This implements the fancier barrier in #278.
It currently will issue a warning if the root ranks waits for 5 seconds. 
Some refactoring of the endrun library was done as well.

Fancy barrier.

---

gadget/params.c
libgadget/cooling_rates.c
libgadget/cooling_rates.h
libgadget/tests/test_cooling.c
libgadget/tests/test_cooling_rates.c

There might be a neater way to implement this, let me know what you think.

Add parameter to rescale hydrogen heat amplitude

---

genic/main.c
genic/params.c
libgadget/blackhole.c
libgadget/cooling.c
libgadget/cooling.h
libgadget/cooling_rates.c
libgadget/cooling_rates.h
libgadget/fof.c
libgadget/petapm.c
libgadget/sfr_eff.c
libgadget/tests/test_cooling.c
libgadget/tests/test_cooling_rates.c

Here are the fixes from today's telecon for the small black hole seed mass and for the ScaleDepVelocity. There is one more fix to make address sanitizer happy.

Fixes from today's telecon

---

gadget/params.c
libgadget/sfr_eff.c

Convert the lyman alpha temperature threshold to a parameter

---

libgenic/power.c

This is more informative for debugging InputPowerRedshift errors.
I was bitten by this again today.

Better powerspec scaling information.

---

libgadget/density.c
libgadget/hydra.c
libgadget/hydra.h
libgadget/slotsmanager.h
libgadget/timestep.c

This moves one of the DhsmlDensityFactor variables into a local variable of density.c, further reducing the overhead of DENSITY_INDEPENDENT_SPH. No change to the hydro example, modest performance increase.

Densitysplit

---

gadget/params.c
libgadget/allvars.h
libgadget/blackhole.c
libgadget/blackhole.h
libgadget/run.c

This means that the BH time when seeding is done will be accounted to BH
and not to FOF/Primary. It also means that we can skip the BH overhead
entirely when there are no BHs yet.

Move halo seeding into run.c

---

libgadget/forcetree.c

Because it is no longer useful!

Remove counting of close pairs when building tree

---

libgadget/forcetree.c
libgadget/tests/test_forcetree.c

A few minor cleanups to the force tree code.

Forcetreecleanup

---

libgadget/blackhole.c
libgadget/drift.c
libgadget/petaio.c
libgadget/slotsmanager.h
libgadget/timebinmgr.c

This removes the sound speed check, removes setting the velocity to the minimum potential particle velocity, and moves an array to be local to blackhole.c, but keeps the repositioning done in drift.c I think this is my preferred solution.

Another change to the black hole repositioning

---

gadget/params.c
libgadget/allvars.h
libgadget/cooling.c
libgadget/cooling.h
libgadget/cooling_rates.c
libgadget/density.c
libgadget/init.c
libgadget/petaio.c
libgadget/run.c
libgadget/sfr_eff.c
libgadget/slotsmanager.h
libgadget/tests/test_cooling.c
libgadget/timestep.c

The minimum energy floor was being applied inconsistently. This PR fixes that and cleans up some aspects of the cooling code.

Fix the minimum energy floor

---

libgadget/blackhole.c
libgadget/drift.c

Two small fixes

---

genic/main.c
libgadget/cosmology.c
libgadget/cosmology.h
libgadget/drift.c
libgadget/gravpm.c
libgadget/init.c
libgadget/lightcone.c
libgadget/neutrinos_lra.c
libgadget/tests/test_cosmology.c
libgadget/tests/test_neutrinos_lra.c
libgadget/tests/test_timefac.c
libgadget/timefac.c
libgadget/timefac.h
libgadget/timestep.c
libgenic/power.c
libgenic/tests/test_power.c
libgenic/zeldovich.c

Pass a Cosmology object around where we need it.

Remove global CP pointer in cosmology.c

---

libgadget/checkpoint.c
libgadget/fof.c
libgadget/fof.h
libgadget/fofpetaio.c
libgadget/run.c
libgadget/runtests.c

Fix the fof code so that instead of setting a global it now passes around a struct.

Localfofvar

---

gadget/params.c
libgadget/blackhole.c

Does this help the small timesteps with the BH?

Fixbhfeedback

---

Makefile.rules
depends/Makefile
libgadget/Makefile
libgadget/domain.c
libgadget/exchange.c
libgadget/fof.c
libgadget/fofpetaio.c
libgadget/init.c
libgadget/tests/test_mpsort.c
libgadget/utils/endrun.h
libgadget/utils/mpsort.c
libgadget/utils/mpsort.h
libgadget/utils/mymalloc.h

This copies MP-Sort to an internal MP-Gadget location, runs the tests automatically and uses MP-Gadget infrastructure.

Internalmpsort

---

libgadget/blackhole.c
libgadget/domain.c
libgadget/exchange.c
libgadget/fofpetaio.c
libgadget/init.c
libgadget/petaio.c
libgadget/run.c
libgadget/sfr_eff.c
libgadget/slotsmanager.c
libgadget/slotsmanager.h
libgadget/tests/test_density.c
libgadget/tests/test_exchange.c
libgadget/tests/test_slotsmanager.c

Various fixes to the FOF Petaio code that slipped by me with the last merge. The largest thing is the gc code, which was using the global tables! Now it uses local variables.

Fofpetaiofix

---

Makefile.rules
Options.mk.example
depends/Makefile
libgadget/Makefile
libgadget/treewalk.c
libgenic/Makefile
platform-options/Options.mk.cori
platform-options/Options.mk.coriknl
platform-options/Options.mk.edison
platform-options/Options.mk.example.coma
platform-options/Options.mk.example.icc
platform-options/Options.mk.macos
platform-options/Options.mk.pfe
platform-options/Options.mk.stampede2
platform-options/Options.mk.travis

Buildcleanups

---

libgadget/cooling.c
libgadget/cooling.h
libgadget/cooling_rates.h
libgadget/cooling_uvfluc.c
libgadget/sfr_eff.c
libgadget/tests/test_cooling.c
tools/HeII_input_file_maker.py
tools/make_HI_reionization_table.py

This PR introduces and cleans up the UV fluctuation script file, and fixes the units bug in MP-Gadget  when loading it. 
@rainwoodman : Are you absolutely sure that pmesh.pm takes Box in Mpc/h and not Mpc?

Hireionscript

---

treewalk.c

Backport some significant optimizations for the treewalk from the master branch
We found that this code made things much slower.

Treewalk backports

---

libgadget/density.c
libgadget/fof.c
libgadget/gravpm.c
libgadget/partmanager.h
libgadget/petapm.c
libgadget/petapm.h
libgadget/run.c
libgadget/timestep.c
libgenic/allvars.h
libgenic/glass.c
libgenic/zeldovich.c

This moves the things in the union{} to their respective modules.

Notransients

---

libgadget/checkpoint.c
libgadget/checkpoint.h
libgadget/forcetree.c
libgadget/hci.h
libgadget/timestep.c

A couple of small cleanups to the HCI code

Hcicleanup

---

tools/convert_bigfile_gadget_format3.py

Fixes to the converter for Gadget-2

---

gadget/params.c
libgadget/cooling_rates.c
libgadget/density.c
libgadget/density.h
libgadget/drift.c
libgadget/hydra.c
libgadget/init.c
libgadget/run.c
libgadget/tests/test_density.c
libgadget/timestep.c

Fix a rare issue found in the frontera run

Fronterafix

---

libgadget/blackhole.c
libgadget/cooling_qso_lightup.c
platform-options/Options.mk.travis

This PR shortens the time over which some of the spinlocks are held and converts some of them to atomics. More locking work ma go in here.

Reducedlock

---

libgadget/density.c
libgadget/sfr_eff.c

Comprehensively fix the short timestep problem for gas around the black holes.

Heatingfix

---

libgadget/blackhole.c
libgadget/forcetree.c

Fix a rare case where gas particles were half swallowed, the black hole merges, and then they are swallowed but not garbage.

Swallowfix

---

gadget/params.c
libgadget/allvars.h
libgadget/cooling.c
libgadget/cooling.h
libgadget/cooling_rates.c
libgadget/cooling_rates.h
libgadget/petaio.c
libgadget/sfr_eff.c
libgadget/sfr_eff.h

For the helium reionization model

Implement outputting helium fractions in the snapshots

---

gadget/params.c
libgadget/fof.c
libgadget/fof.h
libgadget/run.c

Needs some memory shenanigans. This fixes a rare crash when we run out of slots.

Enable allocating more black hole slots when needed

---

.travis.yml
gadget/params.c
install-nbodykit.sh
libgadget/blackhole.c
libgadget/cooling_qso_lightup.c
libgadget/partmanager.h
libgadget/winds.c
libgadget/winds.h

This is the cleanup part of the moreatomic branch, minus the clever use of atomic capture, which I am not convinced should actually work. This branch does actually remove one of the spinlocks!

Physicscleanup

---

libgadget/density.c
libgadget/domain.c
libgadget/gravshort.h
libgadget/hydra.c
libgadget/init.c
libgadget/partmanager.h
libgadget/petaio.c
libgadget/tests/test_density.c
libgadget/tests/test_gravity.c

Remove GravCost and switch to particle load balancing by default. Leave much of the code behind in case we come up with a working work-load balancing algorithm.

Particleloadbalance

---

Options.mk.example
gadget/params.c
libgadget/allvars.h
libgadget/drift.c
libgadget/init.c
libgadget/lightcone.c
libgadget/lightcone.h
libgadget/run.c
libgadget/timestep.c
platform-options/Options.mk.BlueTides
platform-options/Options.mk.cori
platform-options/Options.mk.coriknl
platform-options/Options.mk.edison
platform-options/Options.mk.example.coma
platform-options/Options.mk.example.icc
platform-options/Options.mk.macos
platform-options/Options.mk.pfe
platform-options/Options.mk.stampede2
platform-options/Options.mk.travis

Move it from a compile time to runtime option. It probably still doesn't
work, but it accounts for the internal position offset and it compiles
without warnings.

Do the most basic work to fix LIGHTCONE

---

libgadget/blackhole.c
libgadget/blackhole.h
libgadget/petaio.c
libgadget/run.c
libgadget/sfr_eff.c
libgadget/timestep.c

Some more changes to reduce BH accretion rate.

Bhketodiet

---

libgadget/cooling_rates.c
libgadget/cooling_rates.h
libgadget/cosmology.h
libgadget/tests/test_cooling_rates.c

Morecooltest

---

libgadget/domain.c
libgadget/exchange.c
libgadget/forcetree.c
libgadget/forcetree.h
libgadget/gravpm.c
libgadget/tests/test_forcetree.c
libgadget/treewalk.c

I tried to do the 6000^3 run and these are the collection of fixes from it.

Some fixes for the large Frontera run

---

depends/install_pfft.sh
gadget/main.c
libgadget/density.c
libgadget/density.h
libgadget/exchange.c
libgadget/fofpetaio.c
libgadget/forcetree.c
libgadget/init.c
libgadget/sfr_eff.c
libgadget/timestep.c
libgadget/treewalk.c
libgadget/treewalk.h
libgadget/utils/mymalloc.c
libgadget/utils/system.c
libgadget/winds.c

This is the largedebug PR with the actual debugging code stripped out. For merge, fixes some bugs.

Largedebugmerge

---

libgadget/petaio.c
libgadget/run.c

Fix a bug loading OmegaLambda from the IC header and warn for similar cases.

Fixomegalambda

---

libgadget/blackhole.c
libgadget/density.c
libgadget/density.h
libgadget/hydra.c
libgadget/hydra.h
libgadget/init.c
libgadget/run.c
libgadget/sfr_eff.c
libgadget/sfr_eff.h
libgadget/slotsmanager.c
libgadget/slotsmanager.h
libgadget/tests/test_density.c

A few cleanups made possible by recent PRs. This will shrink peak memory usage but have few other effects.

Predictedcleanup

---

libgadget/cooling_qso_lightup.c
libgadget/gravshort.h
libgadget/treewalk.c
libgadget/treewalk.h
libgadget/winds.c

Reduce the size of the buffer required for exporting particles and increase the maximal export buffer size a bit.

Reducedexportsize

---

tools/rebin_powerspectrum.py

Counts the modes at each bin and so smooths out the jagged parts.

Add an example script to rebin the power spectrum

---

libgadget/treewalk.c
libgadget/treewalk.h
libgadget/winds.c

Some work to reduce the treewalk imbalance time by smarter scheduling.

Guidedtreewalk

---

libgadget/forcetree.c
libgadget/forcetree.h
libgadget/gravpm.c
libgadget/gravshort-tree.c
libgadget/tests/test_forcetree.c
libgadget/treewalk.c

Remove the useless nextnode entry in struct NODE. Just a cleanup.

Nonextnode

---

tools/HeII_input_file_maker.py

It seems being set to linear at the end of the file

Default for hist

---

libgadget/utils/endrun.c
libgadget/utils/system.c
libgadget/utils/system.h

Print ERROR: if message is from endrun.

---

libgadget/tests/test_density.c

Testdensityfixes

---

libgadget/blackhole.c

Fix whitespace in blackhole.c. No semantic changes.

Whitespace cleanups

---

libgadget/allvars.h
libgadget/blackhole.c
libgadget/density.c
libgadget/density.h
libgadget/gravpm.c
libgadget/hydra.c
libgadget/init.c
libgadget/init.h
libgadget/run.c
libgadget/runtests.c
libgadget/sfr_eff.c
libgadget/tests/test_density.c
libgadget/tests/test_timebinmgr.c
libgadget/timebinmgr.c
libgadget/timebinmgr.h
libgadget/timefac.c
libgadget/timefac.h
libgadget/timestep.c
libgadget/timestep.h
libgadget/treewalk.h
libgadget/types.h
libgadget/winds.c

I removed Ti_Current which was embedded deep in the code. I initially started to do something else, but got distracted, hence the strange branch name :-)

Cleanups to remove Ti_Current

---

depends/bigfile/.gitignore
depends/bigfile/bench/suite.sh
depends/bigfile/bigfile/__init__.py
depends/bigfile/bigfile/pyxbigfile.pyx
depends/bigfile/bigfile/tests/test_bigfile.py
depends/bigfile/example/Makefile
depends/bigfile/example/record-mpi.c
depends/bigfile/setup.py
depends/bigfile/src/CMakeLists.txt
depends/bigfile/src/Makefile
depends/bigfile/src/bigfile-internal.h
depends/bigfile/src/bigfile-mpi.c
depends/bigfile/src/bigfile-mpi.h
depends/bigfile/src/bigfile-record.c
depends/bigfile/src/bigfile.c
depends/bigfile/src/bigfile.h
depends/bigfile/utils/CMakeLists.txt
depends/bigfile/utils/Makefile

Bigfile update

---

gadget/params.c
libgadget/fof.c

Suppress BHs in not-yet star forming halos

Add a stellar mass threshold for black hole seeding

---

libgadget/blackhole.c

`fac*= a`  should be outside the loop.

fix a bug in BH_DRAG

---

gadget/params.c
libgadget/blackhole.c

Implements a power law initial mass function for the BH

Implement a power law for the initial BH mass

---

libgadget/metal_return.c
libgadget/petaio.c

Some optimizations for the metal return density finder, copied from the SPH density() code.

Metdensopt

---

libgadget/density.c

This PR uses density gradients to find the smoothing length of the black holes as well as the SPH particles and the stars. This makes density() converge much faster for BHs, at the cost of a small amount of extra memory during density().

Compute DHSML for BHs as well as gas

---

libgadget/blackhole.c
libgadget/density.c
libgadget/density.h
libgadget/hydra.c
libgadget/hydra.h
libgadget/metal_return.c
libgadget/run.c
tools/plotGSMF.py

At Asterix scale, any loop over all particles becomes a bottleneck. This PR removes some of these loops, the initialisation of the predicted quantities and the BH injected_BH_energy loop. More coming.

Largescaling

---

tools/parsebench.py

Builds a tree of entries which python can manipulate.

Add script to parse cpu.txt files

---

libgadget/metal_return.c
libgadget/run.c

Fixmetals2

---

libgadget/metal_return.c

Improve scaling of the star density

Stardensity2

---

libgadget/density.c
libgadget/fof.c
libgadget/gravshort-tree.c
libgadget/metal_return.c
libgadget/run.c
libgadget/treewalk.c
libgadget/treewalk.h
libgadget/winds.c

Some improved balance diagnostics from treewalk

Mergedstardens

---

libgadget/fof.c
libgadget/treewalk.c
libgadget/treewalk.h

Some optimizations to fof secondary labelling.

Fofsecondary

---

libgadget/density.c
libgadget/metal_return.c
libgadget/treewalk.c
libgadget/treewalk.h
libgadget/winds.c

Clean up some of the common duplicated code in density.

Densitycleanup

---

libgadget/neutrinos_lra.c
libgadget/treewalk.c

This is a little large in some places. I will investigate some omp constructs.

Record and report the imbalance in time execution for different threads

---

libgadget/metal_return.c
libgadget/treewalk.c

Densityfix

---

libgadget/petaio.c
libgadget/sfr_eff.c
libgadget/treewalk.c
libgadget/winds.c

Fix a segfault if CoolingOn = 0 and HydroOn = 1.

Smallfixes

---

libgadget/blackhole.c
libgadget/density.c
libgadget/forcetree.c
libgadget/treewalk.c
libgadget/treewalk.h
libgadget/winds.c

A few fairly trivial optimizations to the feedback models.
In particular avoid an ugly loop over all particles in the wind code. We could probably do a similar trick for the swallowing in blackhole, but it is more complicated because you need to also add mass to the BH doing the swallowing (maybe on another processor) and I don't feel like doing the work right now.

Feedbackopt

---

libgadget/fof.c

Implement fast path for fof primary double-check

---

libgadget/blackhole.c

Because BHHeated and IsGarbage are bitfields setting either one may race with the other.
The accretion treewalk both swallowed particles and heated them so the
race was possible if very rare. Th symptom is a zero mass particle
without garbage set.

Fix swallowing race with heating.

---

gadget/params.c
libgadget/hci.c
libgadget/init.c
libgadget/metal_return.c
libgadget/metal_return.h
libgadget/run.c
libgadget/sfr_eff.c
libgadget/winds.c
libgadget/winds.h
tools/plotGSMF.py

We have noticed that the DelayTime is sometimes infinite. It seems likely that the wind velocity v is either zero or NaN in these cases. These are some attempts to fix this.

Some attempts to fix the wind model

---

libgadget/exchange.c
libgadget/fofpetaio.c

Fixes the PIG output when LARGE_EXCHANGE_BROKEN is on

Allow FOF exchanges to have multiple iterations

---

libgadget/exchange.c

Instead of limiting the total size of the outgoing buffer, limit the size that will be sent via each Alltoallv. So instead of the limit being base part + all slots < 2 GB, it is now max((base part), slots) < 2GB . This is a bit less constraining and corresponds better to the things that actually crash.
This is on by default because I have not yet had an exchange that exceeds these bounds succeed.

Replace MPI_LARGE_EXCHANGE_BROKEN with a limit on each alltoall

---

libgadget/blackhole.c

Sometimes the multiple writes were jamming up the filesystem on frontera, so
build one big buffer and write it all.

Batch up fwrite calls for BlackholeDetails

---

gadget/params.c
libgadget/cooling.h
libgadget/cooling_rates.c
libgadget/cooling_uvfluc.c
libgadget/sfr_eff.c
tools/plotGSMF.py

Implement a temperature boost during HI reionization, following 1807.09282. Off by default.

Reiontbump

---

examples/hydro/paramfile.gadget
libgadget/forcetree.c
libgadget/tests/test_forcetree.c

Optimize the treebuild merge with some scheduling.

Treebuildsched

---

libgadget/allvars.h
libgadget/blackhole.c
libgadget/blackhole.h
libgadget/checkpoint.c
libgadget/checkpoint.h
libgadget/cosmology.h
libgadget/fof.c
libgadget/fof.h
libgadget/fofpetaio.c
libgadget/forcetree.c
libgadget/gravshort-tree.c
libgadget/hydra.c
libgadget/hydra.h
libgadget/init.c
libgadget/init.h
libgadget/petaio.c
libgadget/petaio.h
libgadget/run.c
libgadget/runtests.c
libgadget/sfr_eff.c
libgadget/sfr_eff.h
libgadget/timestep.c
libgadget/timestep.h

Long overdue cleanup of the various time variables, which were set every timestep. I was able to disentangle them enough to pass them as variables and remove the All members.

Notimeallvars

---

gadget/params.c
genic/params.c
libgadget/utils/paramset.c
libgadget/utils/paramset.h
libgadget/utils/string.c
libgadget/utils/string.h

Simplify the error handling code for parameter parsing.

Simplerparams

---

examples/hydro/paramfile.gadget
gadget/params.c
libgadget/blackhole.c
libgadget/petaio.c
libgadget/slotsmanager.h

Implementation of TNG kinetic feedback, following the description in Weinberger 2017 MN 465, 3291
[AGN-kinetic-Implementation.pdf](https://github.com/MP-Gadget/MP-Gadget/files/7793964/AGN-kinetic-Implementation.pdf)

AGN kinetic feedback 

---

depends/Makefile
depends/install_pfft.sh

Update pfft to latest release

---

examples/hydro/paramfile.gadget
examples/travis/paramfile.gadget
gadget/params.c
libgadget/blackhole.c
libgadget/checkpoint.c
libgadget/forcetree.c
libgadget/forcetree.h
libgadget/gravity.h
libgadget/gravshort-pair.c
libgadget/gravshort-tree.c
libgadget/gravshort.h
libgadget/partmanager.h
libgadget/run.c
libgadget/runtests.c
libgadget/slotsmanager.h
libgadget/tests/test_gravity.c
libgadget/timestep.c
libgadget/timestep.h
tools/compare_two_plots.py

This implements the hierarchical gravity splitting from Gadget-4. No tests yet but it runs!

Hierarchicalgravity

---

gadget/params.c
libgadget/sfr_eff.c

using the regular cooling time instead of the relaxation time
This should increase the star formation rate in massive galaxies

Implement a new BHFeedbackTcool which has all star forming gas cool

---

libgadget/forcetree.c

Missed one in fixhmaxupdate. Needs to go to astrid-ii as well.

Extra hmax fix to actually use the updated hsml value!

---

libgadget/cooling_qso_lightup.c
libgadget/gdbtools.c
libgadget/init.c
libgadget/partmanager.h
libgadget/petapm.c
libgadget/run.c
libgadget/runtests.c
libgadget/sfr_eff.c
libgadget/timebinmgr.c
libgadget/timestep.c
libgadget/uvbg.c
libgenic/save.c

Some small cleanups after the excursion set merge.

Excursionsetcleanup

---

libgadget/timestep.c

The twotimestep branch had a problem where some short timesteps had no active particles. Fix it! 
Also a couple of cleanups and comments.

Fixsmalltimestep

---

libgadget/slotsmanager.h

reduce memory usage of the star particle struct

reduce memory of star particle slot

---

libgadget/bhdynfric.c
libgadget/bhinfo.c
libgadget/blackhole.c

Cleaner fix than https://github.com/MP-Gadget/MP-Gadget/pull/603/files

Fix BHDynfric off case

---

libgadget/density.c
libgadget/run.c

Fix the edge case where entropy becomes negative.

Fixentropylimit

---

tools/readBHdetail.py

- Corrected the C-datatype specifier for KEflag
- Added some error handling to read a folder seamlessly skipping incomplete files (not in multiple of 436 bytes)
- Additional field in returned array for redshift to preserve time field

Bug fix and mods in readBHdetail.py

---

libgenic/power.c

Fix the transfer function loading when there are DE perturbations present

Omega fld transfer fix

---

libgadget/bhdynfric.c
libgadget/bhdynfric.h
libgadget/bhinfo.c
libgadget/bhinfo.h
libgadget/blackhole.c
libgadget/density.c
libgadget/slotsmanager.h
libgadget/timestep.c

This gives dynamic friction its own timestep, using an acceleration criterion like the gravity timestep. This way we don't need the tree with the stars so often.

Dynfricstep

---

gadget/params.c
libgadget/forcetree.c
libgadget/forcetree.h
libgadget/gravity.h
libgadget/gravpm.c
libgadget/gravshort-pair.c
libgadget/gravshort-tree.c
libgadget/gravshort.h
libgadget/neutrinos_lra.c
libgadget/run.c
libgadget/run.h
libgadget/runtests.c
libgadget/tests/test_density.c
libgadget/tests/test_fof.c
libgadget/tests/test_forcetree.c
libgadget/tests/test_gravity.c
libgadget/timestep.c
libgadget/timestep.h

Cleanups to the neutrino code.

Neutrinocleanup

---

libgadget/timestep.c
libgadget/treewalk.c

Remove some false cacheline sharing in the queue build routines. Negligible speedup, but seems like a good idea.

Cacheline sharing

---

gadget/params.c
libgadget/blackhole.c
libgadget/density.c
libgadget/gravity.h
libgadget/gravshort-pair.c
libgadget/gravshort-tree.c
libgadget/gravshort.h
libgadget/tests/test_gravity.c
libgadget/timestep.c
libgadget/treewalk.c

Remove the adaptive softening feature, which we never really used (it isn't that useful, because it reduces resolution).

Noadaptive

---

gadget/params.c
libgadget/blackhole.c
libgadget/density.c
libgadget/gravity.h
libgadget/gravshort-pair.c
libgadget/gravshort-tree.c
libgadget/gravshort.h
libgadget/tests/test_gravity.c
libgadget/timestep.c
libgadget/treewalk.c

Fixes to the code when the export buffer is full.

Fixfullbuffer

---

README.rst
libgadget/bhinfo.c
libgadget/bhinfo.h
libgadget/blackhole.c
libgadget/cooling_qso_lightup.c
libgadget/density.c
libgadget/fof.c
libgadget/fof.h
libgadget/fofpetaio.c
libgadget/forcetree.c
libgadget/forcetree.h
libgadget/hci.c
libgadget/hci.h
libgadget/init.c
libgadget/petaio.c
libgadget/petaio.h
libgadget/run.c
libgadget/runtests.c
libgadget/sfr_eff.c
libgadget/timestep.c
libgadget/timestep.h
libgadget/treewalk.c
libgadget/utils/system.c
libgadget/utils/system.h
libgadget/veldisp.c
libgadget/winds.c
libgadget/winds.h

Tweaks inspired by the texascale day.

Texatweaks

---

libgadget/domain.c
libgadget/exchange.c
libgadget/forcetree.c
libgadget/forcetree.h
libgadget/init.c
libgadget/run.c
libgadget/runtests.c
libgadget/sfr_eff.c
libgadget/tests/test_density.c
libgadget/tests/test_forcetree.c
libgadget/tests/test_gravity.c
libgadget/timestep.c
libgadget/timestep.h
libgadget/treewalk.c
libgadget/utils/system.c
libgadget/utils/system.h

A cleanup and make the array compaction parallel.

Parallelcompact

---

libgadget/treewalk.c
libgadget/treewalk.h

Some preparation for making the maximum buffer during treewalk larger.

Bigtreebuf

---

gadget/params.c
libgadget/gravity.h
libgadget/gravshort-tree.c
libgadget/gravshort.h
libgadget/runtests.c
libgadget/treewalk.c

Maxbhopeningangle

---

gadget/params.c
genic/params.c
libgadget/cosmology.c
libgadget/cosmology.h
libgadget/petaio.c
libgadget/tests/test_neutrinos_lra.c
libgenic/save.c

Add an option to use the CLASS background cosmology convention

Class cosmology

---

libgadget/treewalk.c
libgadget/treewalk.h

Increase the size of the node list to 4 again, hopefully filling up the buffer less often.

Nodelistlength

---

.github/workflows/main.yaml
libgadget/runtests.c
libgadget/treewalk.c
libgadget/treewalk.h

Attempts to fix the 'export buffer fills up with multiple threads' problem.

Fixbufferfill

---

libgadget/init.c

Print more details on the matter content on startup.

Omegaprint

---

tools/convert_bigfile_gadget_hdf5.py

Fix the conversion script from HDF5 Gadget to bigfile.

Fixconvert

---

libgadget/Makefile
libgadget/exchange.c
libgadget/fof.c
libgadget/fof.h
libgadget/slotsmanager.c
libgadget/slotsmanager.h
libgadget/tests/test_fof.c
libgenic/Makefile

I noticed that the MPI tests were not actually running! The FOF test was also broken.

Fixmpifoftest

---

libgadget/utils/endrun.c

The external tools often don't run after MPI_Abort is called and so aren't that useful. This fixes our fallback use of glibc's backtrace. Change it to be unconditional on a segfault (in case the memory variable for using it gets corrupted), but never do it after endrun (we know where any endrun was called and all the stacktraces are too verbose).

More useful backtrace on a segfault

---

libgadget/density.c
libgadget/forcetree.c
libgadget/forcetree.h
libgadget/petapm.c
libgadget/petapm.h
libgadget/tests/test_density.c
libgadget/tests/test_forcetree.c
libgadget/treewalk.c

In case they overflow (or the compiler does something odd).

Make some petapm variables 64-bit

---

libgadget/timestep.c

This happens because all active gas particles have become stars (or been accreted). We used to look for stars that were just created and use their hydro timestep. However, this can misbehave if the next timestep up also has zero active gas particles.
Instead just re-use the current timestep, making it longer if we can. This should gradually return to the active timeline.

Fix to case where no particles are hydro active
